-- ============================================================================
-- B-List seed, part 1 of 5
-- Adventure & Adrenaline Sports
--   ... Culinary & Beverage Craft
-- ============================================================================
-- 179 items. Split out of 0015 because a single 78 KB statement is
-- a bad thing to paste into a browser SQL editor: a paste that arrives short
-- fails with a parse error somewhere in the middle, which tells you nothing
-- about what actually went wrong.
--
-- Run 0015_bucket_list.sql first for the table itself. Then run these five in
-- any order. Each is idempotent - re-running adds nothing and overwrites
-- nothing you have since ticked off or edited.
-- ============================================================================

insert into public.bucket_items (user_id, category, title, cost, position)
select u.id, v.category, v.title, v.cost, v.position
from auth.users u
cross join (values
    ('Adventure & Adrenaline Sports', 0, 'Skateboarding (learn to ollie)', 'moderate', 0),
    ('Adventure & Adrenaline Sports', 0, 'Longboarding / cruiser boarding', 'moderate', 1),
    ('Adventure & Adrenaline Sports', 0, 'Roller skating', 'moderate', 2),
    ('Adventure & Adrenaline Sports', 0, 'Inline skating (rollerblading)', 'moderate', 3),
    ('Adventure & Adrenaline Sports', 0, 'Mountain biking / trail riding', 'moderate', 4),
    ('Adventure & Adrenaline Sports', 0, 'Go-karting', 'moderate', 5),
    ('Adventure & Adrenaline Sports', 0, 'Motorcycle road trip', 'high', 6),
    ('Adventure & Adrenaline Sports', 0, 'Parkour / freerunning basics', 'low', 7),
    ('Adventure & Adrenaline Sports', 0, 'Sandboarding down a dune', 'moderate', 8),
    ('Adventure & Adrenaline Sports', 0, 'Off-road buggy / dune bashing', 'moderate', 9),
    ('Adventure & Adrenaline Sports', 0, 'Ice skating', 'moderate', 10),
    ('Adventure & Adrenaline Sports', 0, 'Obstacle course racing (Spartan-style)', 'moderate', 11),
    ('Adventure & Adrenaline Sports', 0, 'Ride a roller coaster at a theme park', 'moderate', 12),
    ('Adventure & Adrenaline Sports', 0, 'Visit a water theme park', 'moderate', 13),
    ('Adventure & Adrenaline Sports', 0, 'Zip-lining', 'moderate', 14),
    ('Adventure & Adrenaline Sports', 0, 'Haunted house walkthrough', 'low', 15),
    ('Adventure & Adrenaline Sports', 0, 'Bungee jumping', 'high', 16),
    ('Adventure & Adrenaline Sports', 0, 'Skydiving (tandem jump)', 'high', 17),
    ('Adventure & Adrenaline Sports', 0, 'Paragliding', 'high', 18),
    ('Adventure & Adrenaline Sports', 0, 'Hot air balloon ride', 'high', 19),
    ('Adventure & Adrenaline Sports', 0, 'A proper track day (drive/ride fast, legally)', 'high', 20),
    ('Adventure & Adrenaline Sports', 0, 'Axe throwing', 'moderate', 21),
    ('Adventure & Adrenaline Sports', 0, 'Laser tag', 'moderate', 22),
    ('Adventure & Adrenaline Sports', 0, 'Paintball', 'moderate', 23),
    ('Adventure & Adrenaline Sports', 0, 'Airsoft', 'moderate', 24),
    ('Adventure & Adrenaline Sports', 0, 'Disc golf', 'low', 25),
    ('Water Adventures', 1, 'Learn to swim properly', 'low', 0),
    ('Water Adventures', 1, 'Snorkeling', 'moderate', 1),
    ('Water Adventures', 1, 'Surfing', 'moderate', 2),
    ('Water Adventures', 1, 'Kayaking', 'moderate', 3),
    ('Water Adventures', 1, 'White-water rafting', 'moderate', 4),
    ('Water Adventures', 1, 'Stand-up paddleboarding (SUP)', 'moderate', 5),
    ('Water Adventures', 1, 'Cliff jumping (safe, supervised spot)', 'low', 6),
    ('Water Adventures', 1, 'Free diving (breath-hold)', 'moderate', 7),
    ('Water Adventures', 1, 'Wakeboarding', 'moderate', 8),
    ('Water Adventures', 1, 'Kite surfing', 'high', 9),
    ('Water Adventures', 1, 'Canyoning', 'high', 10),
    ('Water Adventures', 1, 'Scuba diving certification', 'high', 11),
    ('Water Adventures', 1, 'Jet skiing', 'high', 12),
    ('Water Adventures', 1, 'Backwater houseboat stay', 'high', 13),
    ('Combat & Precision Sports', 2, 'Boxing', 'moderate', 0),
    ('Combat & Precision Sports', 2, 'Judo', 'moderate', 1),
    ('Combat & Precision Sports', 2, 'Karate', 'moderate', 2),
    ('Combat & Precision Sports', 2, 'Wrestling (kushti/freestyle)', 'low', 3),
    ('Combat & Precision Sports', 2, 'Taekwondo', 'moderate', 4),
    ('Combat & Precision Sports', 2, 'Brazilian Jiu-Jitsu grappling', 'moderate', 5),
    ('Combat & Precision Sports', 2, 'Muay Thai', 'moderate', 6),
    ('Combat & Precision Sports', 2, 'Silambam (Tamil stick-fighting)', 'moderate', 7),
    ('Combat & Precision Sports', 2, 'Kalaripayattu', 'moderate', 8),
    ('Combat & Precision Sports', 2, 'Krav Maga basics', 'moderate', 9),
    ('Combat & Precision Sports', 2, 'Archery', 'moderate', 10),
    ('Combat & Precision Sports', 2, 'Fencing', 'moderate', 11),
    ('Combat & Precision Sports', 2, 'Javelin throw', 'low', 12),
    ('Combat & Precision Sports', 2, 'Discus / shot put', 'low', 13),
    ('Combat & Precision Sports', 2, 'Darts, played seriously', 'low', 14),
    ('Combat & Precision Sports', 2, 'Billiards/snooker, competitively', 'low', 15),
    ('Combat & Precision Sports', 2, 'Slingshot target practice', 'low', 16),
    ('Combat & Precision Sports', 2, 'Sport shooting at a licensed range', 'moderate', 17),
    ('Combat & Precision Sports', 2, 'Strongman-style event (tire flip, farmer''s carry)', 'moderate', 18),
    ('Combat & Precision Sports', 2, 'Arm wrestling, technique-focused', 'low', 19),
    ('Combat & Precision Sports', 2, 'Grip strength testing (dead hangs, plate pinches)', 'low', 20),
    ('Combat & Precision Sports', 2, 'Tug of war, real team setting', 'low', 21),
    ('Combat & Precision Sports', 2, 'Kettlebell sport lifting', 'moderate', 22),
    ('Team & Individual Sports', 3, 'Join a local cricket/football club', 'low', 0),
    ('Team & Individual Sports', 3, 'Play in a real tournament', 'low', 1),
    ('Team & Individual Sports', 3, 'Badminton, seriously', 'low', 2),
    ('Team & Individual Sports', 3, 'Table tennis, seriously', 'low', 3),
    ('Team & Individual Sports', 3, 'Kabaddi', 'low', 4),
    ('Team & Individual Sports', 3, 'Volleyball', 'low', 5),
    ('Team & Individual Sports', 3, 'Squash', 'moderate', 6),
    ('Team & Individual Sports', 3, 'Running club + official 5K/10K/half race', 'moderate', 7),
    ('Team & Individual Sports', 3, 'Basic gymnastics moves (handstand, cartwheel)', 'low', 8),
    ('Team & Individual Sports', 3, 'A pull-up, if you can''t do one yet', 'low', 9),
    ('Team & Individual Sports', 3, 'Deadlift/squat with proper form', 'moderate', 10),
    ('Team & Individual Sports', 3, 'Cold water plunge', 'low', 11),
    ('Endurance & Personal Records', 4, 'Run a 5K, then a 10K', 'low', 0),
    ('Endurance & Personal Records', 4, 'Century ride (100km cycling)', 'low', 1),
    ('Endurance & Personal Records', 4, 'Swim across a lake / open water', 'low', 2),
    ('Endurance & Personal Records', 4, '24-hour challenge of your own design', 'low', 3),
    ('Endurance & Personal Records', 4, 'Multi-day trek, 50km+ total', 'moderate', 4),
    ('Endurance & Personal Records', 4, 'Full marathon (42.2km)', 'moderate', 5),
    ('Endurance & Personal Records', 4, 'Ultra marathon (50km+)', 'moderate', 6),
    ('Endurance & Personal Records', 4, 'Sprint/Olympic-distance triathlon', 'moderate', 7),
    ('Endurance & Personal Records', 4, 'Obstacle-course ultra race', 'moderate', 8),
    ('Endurance & Personal Records', 4, 'Ironman-distance event, long-term goal', 'high', 9),
    ('Endurance & Personal Records', 4, 'Stair-climbing challenge (a very tall building)', 'low', 10),
    ('Endurance & Personal Records', 4, 'Charity walk/run for a cause', 'low', 11),
    ('Endurance & Personal Records', 4, 'Longest plank held — beat it again a year later', 'low', 12),
    ('Endurance & Personal Records', 4, 'Max pull-ups, tracked over months', 'low', 13),
    ('Endurance & Personal Records', 4, '100+ day activity streak', 'low', 14),
    ('Endurance & Personal Records', 4, '30 days no added sugar', 'low', 15),
    ('Endurance & Personal Records', 4, '30 days of cold showers', 'low', 16),
    ('Endurance & Personal Records', 4, 'Wake up at 5AM for 30 straight days', 'low', 17),
    ('Endurance & Personal Records', 4, 'Read a book cover-to-cover in a day', 'low', 18),
    ('Endurance & Personal Records', 4, 'Hold your breath 2+ min, trained, never alone', 'moderate', 19),
    ('Endurance & Personal Records', 4, 'A full week with no processed food', 'low', 20),
    ('Endurance & Personal Records', 4, 'Journal every day for 100 days', 'low', 21),
    ('Music & Sound', 5, 'Learn an instrument (guitar, keyboard, cajon, etc.)', 'moderate', 0),
    ('Music & Sound', 5, 'Learn to sing properly', 'moderate', 1),
    ('Music & Sound', 5, 'Perform at an open mic', 'low', 2),
    ('Music & Sound', 5, 'Beatboxing', 'low', 3),
    ('Music & Sound', 5, 'DJing basics', 'moderate', 4),
    ('Music & Sound', 5, 'Music production', 'moderate', 5),
    ('Music & Sound', 5, 'Join a band or jam session', 'low', 6),
    ('Music & Sound', 5, 'Carnatic or Hindustani classical basics', 'moderate', 7),
    ('Music & Sound', 5, 'Busk publicly with an instrument or voice', 'low', 8),
    ('Music & Sound', 5, 'Join a choir / singing group', 'low', 9),
    ('Music & Sound', 5, 'Compose an original song', 'low', 10),
    ('Music & Sound', 5, 'Play in an ensemble/orchestra setting', 'low', 11),
    ('Music & Sound', 5, 'Record and release a cover song', 'low', 12),
    ('Visual, Craft & Niche Arts', 6, 'Sketching / drawing', 'low', 0),
    ('Visual, Craft & Niche Arts', 6, 'Painting (acrylic, watercolor)', 'low', 1),
    ('Visual, Craft & Niche Arts', 6, 'Photography — learn manual mode', 'moderate', 2),
    ('Visual, Craft & Niche Arts', 6, 'Street photography walk', 'low', 3),
    ('Visual, Craft & Niche Arts', 6, 'Pottery / clay work', 'moderate', 4),
    ('Visual, Craft & Niche Arts', 6, 'Calligraphy', 'low', 5),
    ('Visual, Craft & Niche Arts', 6, 'Filmmaking — shoot and edit a short video', 'low', 6),
    ('Visual, Craft & Niche Arts', 6, 'Tattoo design (just designing)', 'low', 7),
    ('Visual, Craft & Niche Arts', 6, 'Calligraphy in a non-Latin script', 'low', 8),
    ('Visual, Craft & Niche Arts', 6, 'Origami — go beyond the basic crane', 'low', 9),
    ('Visual, Craft & Niche Arts', 6, 'Sand art', 'low', 10),
    ('Visual, Craft & Niche Arts', 6, 'A genuinely intricate rangoli/kolam design', 'low', 11),
    ('Visual, Craft & Niche Arts', 6, 'Terrarium building', 'low', 12),
    ('Visual, Craft & Niche Arts', 6, 'Quilling (paper filigree art)', 'low', 13),
    ('Visual, Craft & Niche Arts', 6, 'Mosaic art piece', 'moderate', 14),
    ('Visual, Craft & Niche Arts', 6, 'Stained-glass style piece', 'moderate', 15),
    ('Visual, Craft & Niche Arts', 6, 'Glassblowing workshop', 'high', 16),
    ('Visual, Craft & Niche Arts', 6, 'Design and print your own t-shirt', 'low', 17),
    ('Visual, Craft & Niche Arts', 6, 'Basic pattern cutting/tailoring', 'moderate', 18),
    ('Visual, Craft & Niche Arts', 6, 'Thrift and upcycle old clothing', 'low', 19),
    ('Visual, Craft & Niche Arts', 6, 'Embroidery', 'low', 20),
    ('Visual, Craft & Niche Arts', 6, 'Design a logo or personal brand mark', 'low', 21),
    ('Performance & Public Speaking', 7, 'Stand-up comedy — write and perform 5 minutes', 'low', 0),
    ('Performance & Public Speaking', 7, 'Acting / theatre workshop', 'moderate', 1),
    ('Performance & Public Speaking', 7, 'Dance class (freestyle, salsa, hip-hop)', 'moderate', 2),
    ('Performance & Public Speaking', 7, 'Public speaking / Toastmasters', 'low', 3),
    ('Performance & Public Speaking', 7, 'Storytelling night', 'low', 4),
    ('Performance & Public Speaking', 7, 'Improv workshop', 'moderate', 5),
    ('Performance & Public Speaking', 7, 'Flamenco or tango', 'moderate', 6),
    ('Performance & Public Speaking', 7, 'Breakdance or hip-hop choreography, beyond basics', 'moderate', 7),
    ('Performance & Public Speaking', 7, 'A folk dance from a country other than India', 'moderate', 8),
    ('Performance & Public Speaking', 7, 'Give a proper talk to a real audience (TEDx-style)', 'low', 9),
    ('Performance & Public Speaking', 7, 'Host and record a podcast episode', 'low', 10),
    ('Performance & Public Speaking', 7, 'Write and perform a monologue', 'low', 11),
    ('Performance & Public Speaking', 7, 'Help organize and take part in a flash mob', 'low', 12),
    ('Performance & Public Speaking', 7, 'Contribute to a public art installation', 'low', 13),
    ('Performance & Public Speaking', 7, 'Be an extra in a film, ad, or short film', 'low', 14),
    ('Performance & Public Speaking', 7, 'Enter and compete in a talent show', 'low', 15),
    ('Performance & Public Speaking', 7, 'A live radio/community broadcast segment', 'low', 16),
    ('Performance & Public Speaking', 7, 'MC an event — weddings, college fests, gatherings', 'low', 17),
    ('Performance & Public Speaking', 7, 'Get interviewed on camera, watch it back', 'low', 18),
    ('Culinary & Beverage Craft', 8, 'Cook a full meal from scratch, no recipe', 'low', 0),
    ('Culinary & Beverage Craft', 8, 'Bake bread', 'low', 1),
    ('Culinary & Beverage Craft', 8, 'Try an unfamiliar regional cuisine', 'low', 2),
    ('Culinary & Beverage Craft', 8, 'Home-brew something (kombucha, curd cultures)', 'low', 3),
    ('Culinary & Beverage Craft', 8, 'Master proper knife skills', 'low', 4),
    ('Culinary & Beverage Craft', 8, 'Try street food you''ve always been unsure about', 'low', 5),
    ('Culinary & Beverage Craft', 8, 'Mixology — proper mocktails at home', 'low', 6),
    ('Culinary & Beverage Craft', 8, 'Barista skills (shots, steaming, latte art)', 'moderate', 7),
    ('Culinary & Beverage Craft', 8, 'Tea tasting course', 'moderate', 8),
    ('Culinary & Beverage Craft', 8, 'Filter coffee tasting across regional styles', 'low', 9),
    ('Culinary & Beverage Craft', 8, 'Make cheese at home from scratch', 'low', 10),
    ('Culinary & Beverage Craft', 8, 'Ferment your own pickles', 'low', 11),
    ('Culinary & Beverage Craft', 8, 'Make chutneys/condiments completely from scratch', 'low', 12),
    ('Culinary & Beverage Craft', 8, 'Try a non-Indian fermented staple (miso, etc.)', 'low', 13),
    ('Culinary & Beverage Craft', 8, 'Make your own curd culture from scratch', 'low', 14),
    ('Culinary & Beverage Craft', 8, 'Dehydrate fruit/vegetables for preservation', 'low', 15),
    ('Culinary & Beverage Craft', 8, 'Make artisanal ice cream from scratch', 'low', 16),
    ('Culinary & Beverage Craft', 8, 'Make traditional Indian sweets from scratch', 'low', 17),
    ('Culinary & Beverage Craft', 8, 'Temper chocolate properly', 'low', 18),
    ('Culinary & Beverage Craft', 8, 'Make a layered cake completely from scratch', 'low', 19),
    ('Culinary & Beverage Craft', 8, 'Break down a whole chicken/fish yourself', 'low', 20),
    ('Culinary & Beverage Craft', 8, 'Master a mother sauce / base gravy from first principles', 'low', 21),
    ('Culinary & Beverage Craft', 8, 'Cook a multi-course meal for guests, timed', 'low', 22),
    ('Culinary & Beverage Craft', 8, 'Try a food you''re genuinely scared of', 'low', 23),
    ('Culinary & Beverage Craft', 8, 'Do a proper blind taste test with friends', 'low', 24),
    ('Culinary & Beverage Craft', 8, 'Cook one dish from every continent, over time', 'low', 25),
    ('Culinary & Beverage Craft', 8, 'Eat the spiciest thing you can handle', 'low', 26),
    ('Culinary & Beverage Craft', 8, 'Eat a full meal with hands only, mindfully', 'low', 27)
) as v(category, category_order, title, cost, position)
on conflict (user_id, category, title) do nothing;
