-- ============================================================================
-- B-List seed, part 5 of 5
-- Care & Responsibility Skills
--   ... Deep Nature Immersion & Rare Sightings
-- ============================================================================
-- 126 items. Split out of 0015 because a single 78 KB statement is
-- a bad thing to paste into a browser SQL editor: a paste that arrives short
-- fails with a parse error somewhere in the middle, which tells you nothing
-- about what actually went wrong.
--
-- Run 0015_bucket_list.sql first for the table itself. Then run these five in
-- any order. Each is idempotent - re-running adds nothing and overwrites
-- nothing you have since ticked off or edited.
-- ============================================================================

insert into public.bucket_items (user_id, category, title, cost, position)
select u.id, v.category, v.title, v.cost, v.position
from auth.users u
cross join (values
    ('Care & Responsibility Skills', 45, 'Safe infant-handling basics', 'low', 0),
    ('Care & Responsibility Skills', 45, 'Infant/child CPR specifically', 'low', 1),
    ('Care & Responsibility Skills', 45, 'Real responsibilities of pet ownership, a new species', 'low', 2),
    ('Care & Responsibility Skills', 45, 'Basic eldercare skills', 'low', 3),
    ('Care & Responsibility Skills', 45, 'How to babyproof a home properly', 'low', 4),
    ('Care & Responsibility Skills', 45, 'Build a real budget for a dependent', 'low', 5),
    ('Care & Responsibility Skills', 45, 'Volunteer at a place caring for a vulnerable group', 'low', 6),
    ('Care & Responsibility Skills', 45, 'Recognize distress in someone who can''t clearly communicate', 'low', 7),
    ('Care & Responsibility Skills', 45, 'Basic conflict mediation', 'low', 8),
    ('Iconic World Journeys', 46, 'An Antarctica expedition', 'high', 0),
    ('Iconic World Journeys', 46, 'Chase the Northern Lights in the Arctic Circle', 'high', 1),
    ('Iconic World Journeys', 46, 'Ride the Trans-Siberian Railway', 'high', 2),
    ('Iconic World Journeys', 46, 'Drive Route 66, USA, start to finish', 'high', 3),
    ('Iconic World Journeys', 46, 'An African safari (Serengeti or Masai Mara)', 'high', 4),
    ('Iconic World Journeys', 46, 'Overland travel along the historic Silk Road', 'high', 5),
    ('Iconic World Journeys', 46, 'The Trans-Mongolian Railway', 'high', 6),
    ('Iconic World Journeys', 46, 'Cross the Andes overland', 'high', 7),
    ('Iconic World Journeys', 46, 'Cruise the Scandinavian fjords', 'high', 8),
    ('Iconic World Journeys', 46, 'An Australian Outback road trip', 'high', 9),
    ('World Wonders & Landmarks', 47, 'The Pyramids of Giza, Egypt', 'high', 0),
    ('World Wonders & Landmarks', 47, 'The Great Wall of China', 'high', 1),
    ('World Wonders & Landmarks', 47, 'Machu Picchu, Peru', 'high', 2),
    ('World Wonders & Landmarks', 47, 'Petra, Jordan', 'high', 3),
    ('World Wonders & Landmarks', 47, 'The Colosseum, Rome', 'high', 4),
    ('World Wonders & Landmarks', 47, 'Angkor Wat, Cambodia', 'high', 5),
    ('World Wonders & Landmarks', 47, 'Christ the Redeemer, Rio de Janeiro', 'high', 6),
    ('World Wonders & Landmarks', 47, 'The Grand Canyon, USA', 'high', 7),
    ('World Wonders & Landmarks', 47, 'Niagara Falls', 'high', 8),
    ('World Wonders & Landmarks', 47, 'Stonehenge, England', 'high', 9),
    ('World Culinary & Craft Tourism', 48, 'Eat a meal at a Michelin-starred restaurant', 'high', 0),
    ('World Culinary & Craft Tourism', 48, 'Tour a wine region and understand the terroir', 'high', 1),
    ('World Culinary & Craft Tourism', 48, 'Tour a cheese-making region (France, Switzerland)', 'high', 2),
    ('World Culinary & Craft Tourism', 48, 'Tour a chocolate factory, bean to bar', 'moderate', 3),
    ('World Culinary & Craft Tourism', 48, 'Stay at a coffee farm during harvest', 'moderate', 4),
    ('World Culinary & Craft Tourism', 48, 'Stay at a tea plantation', 'moderate', 5),
    ('World Culinary & Craft Tourism', 48, 'Explore a spice market in another country', 'high', 6),
    ('World Culinary & Craft Tourism', 48, 'A full food-market crawl in a foreign city', 'high', 7),
    ('World Culinary & Craft Tourism', 48, 'A cooking class in the home country of that cuisine', 'high', 8),
    ('World Culinary & Craft Tourism', 48, 'Eat at a genuine farm-to-table restaurant', 'moderate', 9),
    ('World Wellness & Traditional Healing', 49, 'A Turkish hammam', 'high', 0),
    ('World Wellness & Traditional Healing', 49, 'A Japanese onsen (hot spring bath)', 'high', 1),
    ('World Wellness & Traditional Healing', 49, 'Traditional Thai massage', 'moderate', 2),
    ('World Wellness & Traditional Healing', 49, 'An Ayurvedic panchakarma treatment, over several days', 'moderate', 3),
    ('World Wellness & Traditional Healing', 49, 'A Russian banya', 'high', 4),
    ('World Wellness & Traditional Healing', 49, 'A Korean jjimjilbang (bathhouse) experience', 'high', 5),
    ('World Wellness & Traditional Healing', 49, 'Balinese traditional healing practices', 'high', 6),
    ('World Wellness & Traditional Healing', 49, 'A Moroccan hammam ritual', 'high', 7),
    ('World Wellness & Traditional Healing', 49, 'Shinrin-yoku (forest bathing), Japanese-style', 'low', 8),
    ('World Wellness & Traditional Healing', 49, 'A Traditional Chinese Medicine consultation', 'moderate', 9),
    ('Spectator Sports & Live World Events', 50, 'Watch a Test cricket match live at a stadium', 'moderate', 0),
    ('Spectator Sports & Live World Events', 50, 'Watch a Grand Slam tennis match', 'high', 1),
    ('Spectator Sports & Live World Events', 50, 'Watch a Formula 1 race live', 'high', 2),
    ('Spectator Sports & Live World Events', 50, 'Watch an Olympic event live, in person', 'high', 3),
    ('Spectator Sports & Live World Events', 50, 'Watch an IPL final live', 'moderate', 4),
    ('Spectator Sports & Live World Events', 50, 'Watch a FIFA World Cup match live', 'high', 5),
    ('Spectator Sports & Live World Events', 50, 'Attend a Super Bowl', 'high', 6),
    ('Spectator Sports & Live World Events', 50, 'Watch a major heavyweight boxing match live', 'high', 7),
    ('Spectator Sports & Live World Events', 50, 'Attend an Ashes cricket series match', 'high', 8),
    ('Spectator Sports & Live World Events', 50, 'Watch a major horse race (Grand National)', 'high', 9),
    ('Winter & Snow Sports', 51, 'Downhill skiing', 'high', 0),
    ('Winter & Snow Sports', 51, 'Snowboarding', 'high', 1),
    ('Winter & Snow Sports', 51, 'Cross-country skiing', 'high', 2),
    ('Winter & Snow Sports', 51, 'Ice climbing', 'high', 3),
    ('Winter & Snow Sports', 51, 'Snowshoeing', 'moderate', 4),
    ('Winter & Snow Sports', 51, 'Dog sledding', 'high', 5),
    ('Winter & Snow Sports', 51, 'A bobsled experience run', 'high', 6),
    ('Winter & Snow Sports', 51, 'Backcountry ski touring', 'high', 7),
    ('Winter & Snow Sports', 51, 'A luge experience', 'high', 8),
    ('Winter & Snow Sports', 51, 'Curling', 'moderate', 9),
    ('Motorsport & Off-Road Riding', 52, 'A rally driving experience day', 'moderate', 0),
    ('Motorsport & Off-Road Riding', 52, 'Motocross', 'moderate', 1),
    ('Motorsport & Off-Road Riding', 52, 'Dirt bike riding on a real trail', 'moderate', 2),
    ('Motorsport & Off-Road Riding', 52, 'Ride in a monster truck', 'moderate', 3),
    ('Motorsport & Off-Road Riding', 52, 'Watch or drive in a demolition derby', 'moderate', 4),
    ('Motorsport & Off-Road Riding', 52, 'Watch or try drag racing', 'moderate', 5),
    ('Motorsport & Off-Road Riding', 52, 'A proper drift car experience', 'moderate', 6),
    ('Motorsport & Off-Road Riding', 52, 'Quad bike racing', 'moderate', 7),
    ('Motorsport & Off-Road Riding', 52, 'Banger racing', 'moderate', 8),
    ('Motorsport & Off-Road Riding', 52, 'A kart endurance race (team format)', 'moderate', 9),
    ('Space & Zero-Gravity Experiences', 53, 'Experience a zero-gravity parabolic flight', 'high', 0),
    ('Space & Zero-Gravity Experiences', 53, 'Register interest in a suborbital spaceflight program', 'high', 1),
    ('Space & Zero-Gravity Experiences', 53, 'Attend a talk where a real astronaut is speaking', 'low', 2),
    ('Space & Zero-Gravity Experiences', 53, 'Tour an actual rocket launch site', 'moderate', 3),
    ('Space & Zero-Gravity Experiences', 53, 'Apply to or follow a citizen space program', 'low', 4),
    ('Space & Zero-Gravity Experiences', 53, 'Visit a space museum''s flown-artifact exhibit', 'low', 5),
    ('Space & Zero-Gravity Experiences', 53, 'Build and launch a high-altitude weather balloon', 'moderate', 6),
    ('Collector''s Deep Cuts', 54, 'Learn sneaker culture and collecting history', 'moderate', 0),
    ('Collector''s Deep Cuts', 54, 'Learn watch collecting — movements, value', 'high', 1),
    ('Collector''s Deep Cuts', 54, 'Start a comic book or trading card collection', 'moderate', 2),
    ('Collector''s Deep Cuts', 54, 'Collect vintage film cameras specifically', 'moderate', 3),
    ('Collector''s Deep Cuts', 54, 'Start collecting original art from local artists', 'moderate', 4),
    ('Collector''s Deep Cuts', 54, 'Pick one niche category and go deep on it', 'moderate', 5),
    ('Modern Recovery & Performance Tech', 55, 'Try a cryotherapy chamber session', 'moderate', 0),
    ('Modern Recovery & Performance Tech', 55, 'Try neurofeedback or biofeedback training', 'moderate', 1),
    ('Modern Recovery & Performance Tech', 55, 'Try an altitude training tent/room session', 'moderate', 2),
    ('Modern Recovery & Performance Tech', 55, 'Try compression therapy (boots or sleeves)', 'moderate', 3),
    ('Modern Recovery & Performance Tech', 55, 'Try an infrared sauna session', 'moderate', 4),
    ('Modern Recovery & Performance Tech', 55, 'Use a wearable deliberately to change one habit', 'low', 5),
    ('Modern Recovery & Performance Tech', 55, 'A real physiotherapy movement-screening assessment', 'moderate', 6),
    ('Working Animals & Falconry', 56, 'Try falconry with a trained bird of prey', 'moderate', 0),
    ('Working Animals & Falconry', 56, 'Watch or learn about sheepdog herding trials', 'low', 1),
    ('Working Animals & Falconry', 56, 'Try mounted archery (horse riding + archery)', 'moderate', 2),
    ('Working Animals & Falconry', 56, 'Learn basic clicker training with a dog', 'low', 3),
    ('Working Animals & Falconry', 56, 'Visit a facility with working dogs', 'low', 4),
    ('Signals, Locks & Hidden Systems', 57, 'Get a ham radio license, make an international contact', 'moderate', 0),
    ('Signals, Locks & Hidden Systems', 57, 'Learn ethical lock-picking (locksport) on your own locks', 'low', 1),
    ('Signals, Locks & Hidden Systems', 57, 'Learn how a mechanical safe/vault mechanism works', 'low', 2),
    ('Signals, Locks & Hidden Systems', 57, 'Learn basic cryptography, solve a real cipher', 'low', 3),
    ('Signals, Locks & Hidden Systems', 57, 'Try metal detecting, with proper permission', 'moderate', 4),
    ('Signals, Locks & Hidden Systems', 57, 'Learn CB radio communication and etiquette', 'low', 5),
    ('Sculpture & Dimensional Art', 58, 'Stone carving — shape a piece from raw stone', 'moderate', 0),
    ('Sculpture & Dimensional Art', 58, 'Wire sculpture — build a figure from bent wire', 'low', 1),
    ('Sculpture & Dimensional Art', 58, 'Ice sculpture, even a simple attempt', 'moderate', 2),
    ('Sculpture & Dimensional Art', 58, 'Plaster casting / mold-making a small object', 'low', 3),
    ('Sculpture & Dimensional Art', 58, 'Weld scrap metal into a piece of art', 'moderate', 4),
    ('Performance Novelties', 59, 'Ventriloquism', 'low', 0),
    ('Performance Novelties', 59, 'Freestyle rap / rap battle', 'low', 1),
    ('Performance Novelties', 59, 'Flair bartending, practiced with empty bottles', 'low', 2),
    ('Performance Novelties', 59, 'Mime performance', 'low', 3),
    ('Performance Novelties', 59, 'Puppeteering your own puppet', 'low', 4),
    ('Deep Nature Immersion & Rare Sightings', 60, 'Attend a firefly-watching event in season', 'low', 0),
    ('Deep Nature Immersion & Rare Sightings', 60, 'A whale-watching expedition', 'high', 1),
    ('Deep Nature Immersion & Rare Sightings', 60, 'A migratory bird-watching event (Siberian cranes)', 'moderate', 2),
    ('Deep Nature Immersion & Rare Sightings', 60, 'A night safari for nocturnal animals', 'moderate', 3),
    ('Deep Nature Immersion & Rare Sightings', 60, 'Olive ridley turtle nesting season, conservation site', 'moderate', 4),
    ('Deep Nature Immersion & Rare Sightings', 60, 'Witness a mass insect emergence event', 'low', 5)
) as v(category, category_order, title, cost, position)
on conflict (user_id, category, title) do nothing;
