-- ============================================================================
-- B-List seed, part 4 of 5
-- Balance & Body Control
--   ... Home Economics & Life Admin Mastery
-- ============================================================================
-- 166 items. Split out of 0015 because a single 78 KB statement is
-- a bad thing to paste into a browser SQL editor: a paste that arrives short
-- fails with a parse error somewhere in the middle, which tells you nothing
-- about what actually went wrong.
--
-- Run 0015_bucket_list.sql first for the table itself. Then run these five in
-- any order. Each is idempotent - re-running adds nothing and overwrites
-- nothing you have since ticked off or edited.
-- ============================================================================

insert into public.bucket_items (user_id, category, title, cost, position)
select u.id, v.category, v.title, v.cost, v.position
from auth.users u
cross join (values
    ('Balance & Body Control', 31, 'Unicycling — learn to ride and turn', 'moderate', 0),
    ('Balance & Body Control', 31, 'Stilts walking', 'low', 1),
    ('Balance & Body Control', 31, 'Freestyle scooter tricks', 'moderate', 2),
    ('Balance & Body Control', 31, 'Longboard dancing (footwork tricks)', 'moderate', 3),
    ('Balance & Body Control', 31, 'Pole fitness basics', 'moderate', 4),
    ('Balance & Body Control', 31, 'Aerial silks / aerial hoop, beginner class', 'moderate', 5),
    ('Balance & Body Control', 31, 'Contortion/backbend basics, safely coached', 'moderate', 6),
    ('Balance & Body Control', 31, 'Advanced yoga poses — handstand, crow, wheel', 'low', 7),
    ('Balance & Body Control', 31, 'Freestyle football/soccer ball tricks', 'low', 8),
    ('Balance & Body Control', 31, 'Breakdancing power moves (headspin, windmill)', 'moderate', 9),
    ('Balance & Body Control', 31, 'Balance board / slack rail training', 'low', 10),
    ('Collecting & Restoration', 32, 'Start a coin collection (numismatics)', 'low', 0),
    ('Collecting & Restoration', 32, 'Start a stamp collection (philately)', 'low', 1),
    ('Collecting & Restoration', 32, 'Collect vinyl records, learn to care for them', 'moderate', 2),
    ('Collecting & Restoration', 32, 'Collect vintage postcards or matchboxes', 'low', 3),
    ('Collecting & Restoration', 32, 'Build a small old-currency collection', 'low', 4),
    ('Collecting & Restoration', 32, 'Restore an old bicycle to working condition', 'moderate', 5),
    ('Collecting & Restoration', 32, 'Restore a vintage mechanical watch', 'moderate', 6),
    ('Collecting & Restoration', 32, 'Restore an old radio or vintage electronics', 'moderate', 7),
    ('Collecting & Restoration', 32, 'Restore an old piece of furniture', 'moderate', 8),
    ('Collecting & Restoration', 32, 'Bring an old film camera back to working order', 'moderate', 9),
    ('Collecting & Restoration', 32, 'Hand-spin yarn from raw fibre', 'low', 10),
    ('Collecting & Restoration', 32, 'Natural-dye a piece of fabric', 'low', 11),
    ('Collecting & Restoration', 32, 'Weave on a traditional handloom', 'moderate', 12),
    ('Collecting & Restoration', 32, 'Learn hand-quilting', 'low', 13),
    ('Collecting & Restoration', 32, 'Make paper by hand from pulp', 'low', 14),
    ('Entrepreneurship & Startup Experiments', 33, 'Build and launch a real MVP', 'low', 0),
    ('Entrepreneurship & Startup Experiments', 33, 'Pitch an idea to a real investor or mentor', 'low', 1),
    ('Entrepreneurship & Startup Experiments', 33, 'Research and open a small online store', 'moderate', 2),
    ('Entrepreneurship & Startup Experiments', 33, 'Try dropshipping as a time-boxed experiment', 'low', 3),
    ('Entrepreneurship & Startup Experiments', 33, 'Paper-trade stocks for a full quarter', 'low', 4),
    ('Entrepreneurship & Startup Experiments', 33, 'Research the real economics of a franchise', 'low', 5),
    ('Entrepreneurship & Startup Experiments', 33, 'Write a full business plan for a fictional idea', 'low', 6),
    ('Entrepreneurship & Startup Experiments', 33, 'Attend a startup pitch night', 'low', 7),
    ('Entrepreneurship & Startup Experiments', 33, 'Deliberately network at a professional event', 'low', 8),
    ('Entrepreneurship & Startup Experiments', 33, 'Build a personal brand on one platform', 'low', 9),
    ('Entrepreneurship & Startup Experiments', 33, 'Cold-email someone you admire professionally', 'low', 10),
    ('Entrepreneurship & Startup Experiments', 33, 'Run a small paid ad campaign and measure it', 'moderate', 11),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Join a Model United Nations conference', 'low', 0),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Participate in a mock trial', 'low', 1),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Enter a formal debate tournament', 'low', 2),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Be a guest on someone else''s podcast', 'low', 3),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Write an op-ed and get it published', 'low', 4),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Defend an argument publicly against real pushback', 'low', 5),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Enter a spelling or word-based competition', 'low', 6),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Compete in speedcubing at an actual event', 'moderate', 7),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Enter a competitive programming contest', 'low', 8),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Compete in a formal rated chess tournament', 'low', 9),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Take part in a quiz/trivia competition', 'low', 10),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Try a competitive Toastmasters speech contest', 'low', 11),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Try underwater photography', 'moderate', 0),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Spearfishing, licensed and supervised', 'moderate', 1),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Go tide-pooling and identify what you find', 'low', 2),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Experience pearl diving (guided experience)', 'high', 3),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Go mushroom foraging with a real expert', 'moderate', 4),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Collect and identify rocks/minerals/crystals', 'low', 5),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Go fossil hunting at a known site', 'moderate', 6),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Basic amateur entomology — collect and identify insects', 'low', 7),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Set up a home weather station and log data', 'moderate', 8),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Learn celestial navigation with a sextant', 'moderate', 9),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Track cloud types over a month', 'low', 10),
    ('Sailing, Rowing & Wind Sports', 36, 'Sail a dinghy, learn to helm it yourself', 'moderate', 0),
    ('Sailing, Rowing & Wind Sports', 36, 'Windsurfing', 'moderate', 1),
    ('Sailing, Rowing & Wind Sports', 36, 'Rowing / crew (single scull or team)', 'moderate', 2),
    ('Sailing, Rowing & Wind Sports', 36, 'Dragon boat racing', 'moderate', 3),
    ('Sailing, Rowing & Wind Sports', 36, 'Multi-day canoe touring', 'moderate', 4),
    ('Sailing, Rowing & Wind Sports', 36, 'Crew on a yacht race', 'high', 5),
    ('Sailing, Rowing & Wind Sports', 36, 'Learn sailing-specific knots and rigging', 'low', 6),
    ('Sailing, Rowing & Wind Sports', 36, 'Hang gliding', 'high', 7),
    ('Sailing, Rowing & Wind Sports', 36, 'Gliding — an unpowered aircraft with an instructor', 'high', 8),
    ('Sailing, Rowing & Wind Sports', 36, 'A short microlight flight experience', 'high', 9),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn basic accounting — debits and credits', 'low', 0),
    ('Financial & Business Literacy Deep-Dive', 37, 'Read and analyze a real company''s annual report', 'low', 1),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn crypto fundamentals, set up a wallet securely', 'low', 2),
    ('Financial & Business Literacy Deep-Dive', 37, 'A full investment analysis of a real property', 'low', 3),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn options/derivatives basics, conceptually', 'low', 4),
    ('Financial & Business Literacy Deep-Dive', 37, 'Build and maintain a personal net-worth tracker', 'low', 5),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn basic actuarial/insurance math', 'low', 6),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn how to value a small business', 'low', 7),
    ('Financial & Business Literacy Deep-Dive', 37, 'Understand mutual fund expense ratios deeply', 'low', 8),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn a real negotiation framework (BATNA)', 'low', 9),
    ('Pilgrimage & Sacred Journeys', 38, 'Char Dham Yatra', 'high', 0),
    ('Pilgrimage & Sacred Journeys', 38, 'Kailash Mansarovar trek', 'high', 1),
    ('Pilgrimage & Sacred Journeys', 38, 'Amarnath Yatra', 'high', 2),
    ('Pilgrimage & Sacred Journeys', 38, 'Sabarimala pilgrimage', 'moderate', 3),
    ('Pilgrimage & Sacred Journeys', 38, 'Camino de Santiago, Spain', 'high', 4),
    ('Pilgrimage & Sacred Journeys', 38, 'Visit the Vatican and St. Peter''s Basilica', 'high', 5),
    ('Pilgrimage & Sacred Journeys', 38, 'Visit Jerusalem''s Old City', 'high', 6),
    ('Pilgrimage & Sacred Journeys', 38, 'Walk a sacred river''s full ghat stretch', 'moderate', 7),
    ('Pilgrimage & Sacred Journeys', 38, 'Golden Temple, Amritsar + volunteer in langar', 'moderate', 8),
    ('Pilgrimage & Sacred Journeys', 38, 'Buddhist stupa circuit (Bodh Gaya, Sarnath)', 'moderate', 9),
    ('Advanced Photography & Visual Storytelling', 39, 'Shoot a time-lapse photography project', 'moderate', 0),
    ('Advanced Photography & Visual Storytelling', 39, 'Try drone cinematography', 'moderate', 1),
    ('Advanced Photography & Visual Storytelling', 39, 'Go on a dedicated wildlife photography expedition', 'high', 2),
    ('Advanced Photography & Visual Storytelling', 39, 'Shoot a full portrait photography series', 'moderate', 3),
    ('Advanced Photography & Visual Storytelling', 39, 'Shoot on film, develop it yourself', 'moderate', 4),
    ('Advanced Photography & Visual Storytelling', 39, 'Try long-exposure light painting', 'low', 5),
    ('Advanced Photography & Visual Storytelling', 39, 'Build a documentary-style photo essay', 'low', 6),
    ('Advanced Photography & Visual Storytelling', 39, 'Macro photography of insects or plants', 'moderate', 7),
    ('Advanced Photography & Visual Storytelling', 39, 'Architecture/panoramic photography of a cityscape', 'low', 8),
    ('Advanced Photography & Visual Storytelling', 39, 'A conceptual self-portrait photography project', 'low', 9),
    ('Circus & Aerial Arts', 40, 'Tightrope walking', 'moderate', 0),
    ('Circus & Aerial Arts', 40, 'Trapeze basics', 'moderate', 1),
    ('Circus & Aerial Arts', 40, 'Aerial rope (corde lisse)', 'moderate', 2),
    ('Circus & Aerial Arts', 40, 'Cyr wheel basics', 'moderate', 3),
    ('Circus & Aerial Arts', 40, 'Hula hoop tricks / hoop dance', 'low', 4),
    ('Circus & Aerial Arts', 40, 'Plate spinning', 'low', 5),
    ('Circus & Aerial Arts', 40, 'Acrobalance / partner acrobatics', 'moderate', 6),
    ('Circus & Aerial Arts', 40, 'A human pyramid team stunt', 'low', 7),
    ('Circus & Aerial Arts', 40, 'A clowning workshop', 'moderate', 8),
    ('Circus & Aerial Arts', 40, 'Staff or baton twirling', 'low', 9),
    ('Grooming, Styling & Body Literacy', 41, 'Basic men''s haircutting — a simple fade or trim', 'low', 0),
    ('Grooming, Styling & Body Literacy', 41, 'Basic women''s haircutting basics', 'low', 1),
    ('Grooming, Styling & Body Literacy', 41, 'Which hairstyles suit which face shapes', 'low', 2),
    ('Grooming, Styling & Body Literacy', 41, 'Style your own hair type properly', 'low', 3),
    ('Grooming, Styling & Body Literacy', 41, 'Basic blow-drying and heat-styling technique', 'low', 4),
    ('Grooming, Styling & Body Literacy', 41, 'Beard grooming and shaping properly', 'low', 5),
    ('Grooming, Styling & Body Literacy', 41, 'Basic braiding techniques', 'low', 6),
    ('Grooming, Styling & Body Literacy', 41, 'How barbers/stylists structure a haircut', 'low', 7),
    ('Grooming, Styling & Body Literacy', 41, 'A proper men''s skincare routine', 'low', 8),
    ('Grooming, Styling & Body Literacy', 41, 'A proper women''s skincare routine, reading labels', 'low', 9),
    ('Grooming, Styling & Body Literacy', 41, 'Learn your own skin type', 'low', 10),
    ('Grooming, Styling & Body Literacy', 41, 'Basic makeup application', 'low', 11),
    ('Grooming, Styling & Body Literacy', 41, 'Dress for your specific body type', 'low', 12),
    ('Grooming, Styling & Body Literacy', 41, 'Correct nail care and hygiene basics', 'low', 13),
    ('Grooming, Styling & Body Literacy', 41, 'How deodorant and body odor actually work', 'low', 14),
    ('Grooming, Styling & Body Literacy', 41, 'Essentials of male hormonal health', 'low', 15),
    ('Grooming, Styling & Body Literacy', 41, 'Essentials of female hormonal health', 'low', 16),
    ('Grooming, Styling & Body Literacy', 41, 'Doctor-recommended self-exams for early detection', 'low', 17),
    ('Grooming, Styling & Body Literacy', 41, 'Basic reproductive health facts, credible source', 'low', 18),
    ('Grooming, Styling & Body Literacy', 41, 'How metabolism differs between men and women', 'low', 19),
    ('Grooming, Styling & Body Literacy', 41, 'What changes to expect in the body with age', 'low', 20),
    ('Grooming, Styling & Body Literacy', 41, 'Common nutrient deficiencies by sex', 'low', 21),
    ('Grooming, Styling & Body Literacy', 41, 'How sleep, stress, and hormones interact', 'low', 22),
    ('Practical Safety & Everyday Preparedness', 42, 'A defensive driving course', 'moderate', 0),
    ('Practical Safety & Everyday Preparedness', 42, 'Change a flat tire yourself', 'low', 1),
    ('Practical Safety & Everyday Preparedness', 42, 'Jump-start a car battery', 'low', 2),
    ('Practical Safety & Everyday Preparedness', 42, 'Basic car maintenance (oil, tires, brakes)', 'low', 3),
    ('Practical Safety & Everyday Preparedness', 42, 'Use a fire extinguisher properly', 'low', 4),
    ('Practical Safety & Everyday Preparedness', 42, 'Earthquake and disaster preparedness for your region', 'low', 5),
    ('Practical Safety & Everyday Preparedness', 42, 'Recognize and avoid common scams', 'low', 6),
    ('Practical Safety & Everyday Preparedness', 42, 'Basic water-rescue technique', 'low', 7),
    ('Practical Safety & Everyday Preparedness', 42, 'Build a proper personal emergency kit', 'low', 8),
    ('Practical Safety & Everyday Preparedness', 42, 'First 5 minutes of common emergencies', 'low', 9),
    ('Practical Safety & Everyday Preparedness', 42, 'De-escalate a public safety situation calmly', 'low', 10),
    ('Practical Safety & Everyday Preparedness', 42, 'Basic home security — what actually deters break-ins', 'low', 11),
    ('Etiquette, Manners & Social Craft', 43, 'Formal dining etiquette', 'low', 0),
    ('Etiquette, Manners & Social Craft', 43, 'Tie at least 3 different tie knots', 'low', 1),
    ('Etiquette, Manners & Social Craft', 43, 'Correct table-setting for a formal meal', 'low', 2),
    ('Etiquette, Manners & Social Craft', 43, 'Business card and introduction etiquette', 'low', 3),
    ('Etiquette, Manners & Social Craft', 43, 'Write a proper formal letter/thank-you note', 'low', 4),
    ('Etiquette, Manners & Social Craft', 43, 'Basic ballroom dance steps (waltz/foxtrot)', 'moderate', 5),
    ('Etiquette, Manners & Social Craft', 43, 'Properly introduce two people to each other', 'low', 6),
    ('Etiquette, Manners & Social Craft', 43, 'Small talk techniques for a room of strangers', 'low', 7),
    ('Etiquette, Manners & Social Craft', 43, 'Hosting etiquette — being a good guest and host', 'low', 8),
    ('Etiquette, Manners & Social Craft', 43, 'Gracefully exit an unwanted conversation', 'low', 9),
    ('Home Economics & Life Admin Mastery', 44, 'Iron a shirt properly, collar and cuffs included', 'low', 0),
    ('Home Economics & Life Admin Mastery', 44, 'Sew a button and fix a hem by hand', 'low', 1),
    ('Home Economics & Life Admin Mastery', 44, 'An efficient clothes-folding system', 'low', 2),
    ('Home Economics & Life Admin Mastery', 44, 'A proper system for organizing important documents', 'low', 3),
    ('Home Economics & Life Admin Mastery', 44, 'A real meal-prep planning system for a busy week', 'low', 4),
    ('Home Economics & Life Admin Mastery', 44, 'Declutter a space using a real method', 'low', 5),
    ('Home Economics & Life Admin Mastery', 44, 'Pack a bag for a trip so nothing''s forgotten', 'low', 6),
    ('Home Economics & Life Admin Mastery', 44, 'A simple personal filing system, digital and physical', 'low', 7),
    ('Home Economics & Life Admin Mastery', 44, 'Basic stain removal for different fabric types', 'low', 8),
    ('Home Economics & Life Admin Mastery', 44, 'Properly store and preserve pantry staples', 'low', 9)
) as v(category, category_order, title, cost, position)
on conflict (user_id, category, title) do nothing;
