-- ============================================================================
-- B-List: the bucket list
-- ============================================================================
-- 818 items in 61 categories, imported from the standalone page that held them
-- in localStorage. Moving them here is the point of the exercise: a list kept
-- in one browser is a list you cannot tick off from your phone, and losing that
-- browser's site data loses years of it.
--
-- COST, NOT IMPORTANCE. The original sorted low-to-high "by what it costs to
-- actually do it", and the three tiers were labelled NO/LOW COST, MODERATE and
-- BIG INVESTMENT. Preserved as low / moderate / high, because that is the
-- question the list is organised around: what can I do this weekend for
-- nothing, versus what needs saving for.
--
-- SEEDED PER USER, by cross joining auth.users. This app has one user, and
-- hardcoding their uuid into a migration would be both ugly and wrong for
-- anyone else who ever runs it. New accounts start empty rather than
-- inheriting someone else's bucket list, which is the correct default for a
-- list this personal.
-- ============================================================================

create table if not exists public.bucket_items (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid        not null,
  category     text        not null,
  title        text        not null check (length(trim(title)) > 0),
  -- What it costs to do, not how much you want it.
  cost         text        not null default 'moderate'
                 check (cost in ('low', 'moderate', 'high')),
  is_done      boolean     not null default false,
  -- The day you did it. Null while undone; set when ticked, so the list can
  -- answer "what did I actually do this year" rather than only "how many".
  done_on      date,
  note         text        not null default '',
  -- Keeps the original order within a category, which was itself meaningful:
  -- the source list was sorted cheapest-first.
  position     integer     not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  -- The same thing twice in one category is a duplicate, not two goals.
  unique (user_id, category, title)
);

create index if not exists bucket_items_user_idx
  on public.bucket_items (user_id, category, position);

-- Answers the two headline figures - how many done, and how many of each cost
-- tier are left - without scanning the whole list.
create index if not exists bucket_items_progress_idx
  on public.bucket_items (user_id, is_done, cost);

drop trigger if exists bucket_items_set_updated_at on public.bucket_items;
create trigger bucket_items_set_updated_at before update on public.bucket_items
  for each row execute function public.set_updated_at();

-- ROW LEVEL SECURITY ----------------------------------------------------------
-- The same four-policy template as every other table in this app.
do $$
begin
  execute 'alter table public.bucket_items enable row level security';

  execute 'drop policy if exists "bucket_items_select_own" on public.bucket_items';
  execute 'drop policy if exists "bucket_items_insert_own" on public.bucket_items';
  execute 'drop policy if exists "bucket_items_update_own" on public.bucket_items';
  execute 'drop policy if exists "bucket_items_delete_own" on public.bucket_items';

  execute 'create policy "bucket_items_select_own" on public.bucket_items
    for select using (user_id = auth.uid())';
  execute 'create policy "bucket_items_insert_own" on public.bucket_items
    for insert with check (user_id = auth.uid())';
  execute 'create policy "bucket_items_update_own" on public.bucket_items
    for update using (user_id = auth.uid()) with check (user_id = auth.uid())';
  execute 'create policy "bucket_items_delete_own" on public.bucket_items
    for delete using (user_id = auth.uid())';
end $$;

-- THE LIST --------------------------------------------------------------------
-- `on conflict do nothing` so re-running this is harmless: it will not
-- duplicate what is already there, and it will not overwrite anything you have
-- since ticked off or edited.
insert into public.bucket_items (user_id, category, title, cost, position)
select u.id, v.category, v.title, v.cost, v.position
from auth.users u
cross join (values
    ('Adventure & Adrenaline Sports', 0, 'Skateboarding (learn to ollie)', 'moderate', 0),
    ('Adventure & Adrenaline Sports', 0, 'Longboarding / cruiser boarding', 'moderate', 1),
    ('Adventure & Adrenaline Sports', 0, 'Roller skating', 'moderate', 2),
    ('Adventure & Adrenaline Sports', 0, 'Inline skating (rollerblading)', 'moderate', 3),
    ('Adventure & Adrenaline Sports', 0, 'Mountain biking / trail riding', 'moderate', 4),
    ('Adventure & Adrenaline Sports', 0, 'Go-karting', 'moderate', 5),
    ('Adventure & Adrenaline Sports', 0, 'Motorcycle road trip', 'high', 6),
    ('Adventure & Adrenaline Sports', 0, 'Parkour / freerunning basics', 'low', 7),
    ('Adventure & Adrenaline Sports', 0, 'Sandboarding down a dune', 'moderate', 8),
    ('Adventure & Adrenaline Sports', 0, 'Off-road buggy / dune bashing', 'moderate', 9),
    ('Adventure & Adrenaline Sports', 0, 'Ice skating', 'moderate', 10),
    ('Adventure & Adrenaline Sports', 0, 'Obstacle course racing (Spartan-style)', 'moderate', 11),
    ('Adventure & Adrenaline Sports', 0, 'Ride a roller coaster at a theme park', 'moderate', 12),
    ('Adventure & Adrenaline Sports', 0, 'Visit a water theme park', 'moderate', 13),
    ('Adventure & Adrenaline Sports', 0, 'Zip-lining', 'moderate', 14),
    ('Adventure & Adrenaline Sports', 0, 'Haunted house walkthrough', 'low', 15),
    ('Adventure & Adrenaline Sports', 0, 'Bungee jumping', 'high', 16),
    ('Adventure & Adrenaline Sports', 0, 'Skydiving (tandem jump)', 'high', 17),
    ('Adventure & Adrenaline Sports', 0, 'Paragliding', 'high', 18),
    ('Adventure & Adrenaline Sports', 0, 'Hot air balloon ride', 'high', 19),
    ('Adventure & Adrenaline Sports', 0, 'A proper track day (drive/ride fast, legally)', 'high', 20),
    ('Adventure & Adrenaline Sports', 0, 'Axe throwing', 'moderate', 21),
    ('Adventure & Adrenaline Sports', 0, 'Laser tag', 'moderate', 22),
    ('Adventure & Adrenaline Sports', 0, 'Paintball', 'moderate', 23),
    ('Adventure & Adrenaline Sports', 0, 'Airsoft', 'moderate', 24),
    ('Adventure & Adrenaline Sports', 0, 'Disc golf', 'low', 25),
    ('Water Adventures', 1, 'Learn to swim properly', 'low', 0),
    ('Water Adventures', 1, 'Snorkeling', 'moderate', 1),
    ('Water Adventures', 1, 'Surfing', 'moderate', 2),
    ('Water Adventures', 1, 'Kayaking', 'moderate', 3),
    ('Water Adventures', 1, 'White-water rafting', 'moderate', 4),
    ('Water Adventures', 1, 'Stand-up paddleboarding (SUP)', 'moderate', 5),
    ('Water Adventures', 1, 'Cliff jumping (safe, supervised spot)', 'low', 6),
    ('Water Adventures', 1, 'Free diving (breath-hold)', 'moderate', 7),
    ('Water Adventures', 1, 'Wakeboarding', 'moderate', 8),
    ('Water Adventures', 1, 'Kite surfing', 'high', 9),
    ('Water Adventures', 1, 'Canyoning', 'high', 10),
    ('Water Adventures', 1, 'Scuba diving certification', 'high', 11),
    ('Water Adventures', 1, 'Jet skiing', 'high', 12),
    ('Water Adventures', 1, 'Backwater houseboat stay', 'high', 13),
    ('Combat & Precision Sports', 2, 'Boxing', 'moderate', 0),
    ('Combat & Precision Sports', 2, 'Judo', 'moderate', 1),
    ('Combat & Precision Sports', 2, 'Karate', 'moderate', 2),
    ('Combat & Precision Sports', 2, 'Wrestling (kushti/freestyle)', 'low', 3),
    ('Combat & Precision Sports', 2, 'Taekwondo', 'moderate', 4),
    ('Combat & Precision Sports', 2, 'Brazilian Jiu-Jitsu grappling', 'moderate', 5),
    ('Combat & Precision Sports', 2, 'Muay Thai', 'moderate', 6),
    ('Combat & Precision Sports', 2, 'Silambam (Tamil stick-fighting)', 'moderate', 7),
    ('Combat & Precision Sports', 2, 'Kalaripayattu', 'moderate', 8),
    ('Combat & Precision Sports', 2, 'Krav Maga basics', 'moderate', 9),
    ('Combat & Precision Sports', 2, 'Archery', 'moderate', 10),
    ('Combat & Precision Sports', 2, 'Fencing', 'moderate', 11),
    ('Combat & Precision Sports', 2, 'Javelin throw', 'low', 12),
    ('Combat & Precision Sports', 2, 'Discus / shot put', 'low', 13),
    ('Combat & Precision Sports', 2, 'Darts, played seriously', 'low', 14),
    ('Combat & Precision Sports', 2, 'Billiards/snooker, competitively', 'low', 15),
    ('Combat & Precision Sports', 2, 'Slingshot target practice', 'low', 16),
    ('Combat & Precision Sports', 2, 'Sport shooting at a licensed range', 'moderate', 17),
    ('Combat & Precision Sports', 2, 'Strongman-style event (tire flip, farmer''s carry)', 'moderate', 18),
    ('Combat & Precision Sports', 2, 'Arm wrestling, technique-focused', 'low', 19),
    ('Combat & Precision Sports', 2, 'Grip strength testing (dead hangs, plate pinches)', 'low', 20),
    ('Combat & Precision Sports', 2, 'Tug of war, real team setting', 'low', 21),
    ('Combat & Precision Sports', 2, 'Kettlebell sport lifting', 'moderate', 22),
    ('Team & Individual Sports', 3, 'Join a local cricket/football club', 'low', 0),
    ('Team & Individual Sports', 3, 'Play in a real tournament', 'low', 1),
    ('Team & Individual Sports', 3, 'Badminton, seriously', 'low', 2),
    ('Team & Individual Sports', 3, 'Table tennis, seriously', 'low', 3),
    ('Team & Individual Sports', 3, 'Kabaddi', 'low', 4),
    ('Team & Individual Sports', 3, 'Volleyball', 'low', 5),
    ('Team & Individual Sports', 3, 'Squash', 'moderate', 6),
    ('Team & Individual Sports', 3, 'Running club + official 5K/10K/half race', 'moderate', 7),
    ('Team & Individual Sports', 3, 'Basic gymnastics moves (handstand, cartwheel)', 'low', 8),
    ('Team & Individual Sports', 3, 'A pull-up, if you can''t do one yet', 'low', 9),
    ('Team & Individual Sports', 3, 'Deadlift/squat with proper form', 'moderate', 10),
    ('Team & Individual Sports', 3, 'Cold water plunge', 'low', 11),
    ('Endurance & Personal Records', 4, 'Run a 5K, then a 10K', 'low', 0),
    ('Endurance & Personal Records', 4, 'Century ride (100km cycling)', 'low', 1),
    ('Endurance & Personal Records', 4, 'Swim across a lake / open water', 'low', 2),
    ('Endurance & Personal Records', 4, '24-hour challenge of your own design', 'low', 3),
    ('Endurance & Personal Records', 4, 'Multi-day trek, 50km+ total', 'moderate', 4),
    ('Endurance & Personal Records', 4, 'Full marathon (42.2km)', 'moderate', 5),
    ('Endurance & Personal Records', 4, 'Ultra marathon (50km+)', 'moderate', 6),
    ('Endurance & Personal Records', 4, 'Sprint/Olympic-distance triathlon', 'moderate', 7),
    ('Endurance & Personal Records', 4, 'Obstacle-course ultra race', 'moderate', 8),
    ('Endurance & Personal Records', 4, 'Ironman-distance event, long-term goal', 'high', 9),
    ('Endurance & Personal Records', 4, 'Stair-climbing challenge (a very tall building)', 'low', 10),
    ('Endurance & Personal Records', 4, 'Charity walk/run for a cause', 'low', 11),
    ('Endurance & Personal Records', 4, 'Longest plank held — beat it again a year later', 'low', 12),
    ('Endurance & Personal Records', 4, 'Max pull-ups, tracked over months', 'low', 13),
    ('Endurance & Personal Records', 4, '100+ day activity streak', 'low', 14),
    ('Endurance & Personal Records', 4, '30 days no added sugar', 'low', 15),
    ('Endurance & Personal Records', 4, '30 days of cold showers', 'low', 16),
    ('Endurance & Personal Records', 4, 'Wake up at 5AM for 30 straight days', 'low', 17),
    ('Endurance & Personal Records', 4, 'Read a book cover-to-cover in a day', 'low', 18),
    ('Endurance & Personal Records', 4, 'Hold your breath 2+ min, trained, never alone', 'moderate', 19),
    ('Endurance & Personal Records', 4, 'A full week with no processed food', 'low', 20),
    ('Endurance & Personal Records', 4, 'Journal every day for 100 days', 'low', 21),
    ('Music & Sound', 5, 'Learn an instrument (guitar, keyboard, cajon, etc.)', 'moderate', 0),
    ('Music & Sound', 5, 'Learn to sing properly', 'moderate', 1),
    ('Music & Sound', 5, 'Perform at an open mic', 'low', 2),
    ('Music & Sound', 5, 'Beatboxing', 'low', 3),
    ('Music & Sound', 5, 'DJing basics', 'moderate', 4),
    ('Music & Sound', 5, 'Music production', 'moderate', 5),
    ('Music & Sound', 5, 'Join a band or jam session', 'low', 6),
    ('Music & Sound', 5, 'Carnatic or Hindustani classical basics', 'moderate', 7),
    ('Music & Sound', 5, 'Busk publicly with an instrument or voice', 'low', 8),
    ('Music & Sound', 5, 'Join a choir / singing group', 'low', 9),
    ('Music & Sound', 5, 'Compose an original song', 'low', 10),
    ('Music & Sound', 5, 'Play in an ensemble/orchestra setting', 'low', 11),
    ('Music & Sound', 5, 'Record and release a cover song', 'low', 12),
    ('Visual, Craft & Niche Arts', 6, 'Sketching / drawing', 'low', 0),
    ('Visual, Craft & Niche Arts', 6, 'Painting (acrylic, watercolor)', 'low', 1),
    ('Visual, Craft & Niche Arts', 6, 'Photography — learn manual mode', 'moderate', 2),
    ('Visual, Craft & Niche Arts', 6, 'Street photography walk', 'low', 3),
    ('Visual, Craft & Niche Arts', 6, 'Pottery / clay work', 'moderate', 4),
    ('Visual, Craft & Niche Arts', 6, 'Calligraphy', 'low', 5),
    ('Visual, Craft & Niche Arts', 6, 'Filmmaking — shoot and edit a short video', 'low', 6),
    ('Visual, Craft & Niche Arts', 6, 'Tattoo design (just designing)', 'low', 7),
    ('Visual, Craft & Niche Arts', 6, 'Calligraphy in a non-Latin script', 'low', 8),
    ('Visual, Craft & Niche Arts', 6, 'Origami — go beyond the basic crane', 'low', 9),
    ('Visual, Craft & Niche Arts', 6, 'Sand art', 'low', 10),
    ('Visual, Craft & Niche Arts', 6, 'A genuinely intricate rangoli/kolam design', 'low', 11),
    ('Visual, Craft & Niche Arts', 6, 'Terrarium building', 'low', 12),
    ('Visual, Craft & Niche Arts', 6, 'Quilling (paper filigree art)', 'low', 13),
    ('Visual, Craft & Niche Arts', 6, 'Mosaic art piece', 'moderate', 14),
    ('Visual, Craft & Niche Arts', 6, 'Stained-glass style piece', 'moderate', 15),
    ('Visual, Craft & Niche Arts', 6, 'Glassblowing workshop', 'high', 16),
    ('Visual, Craft & Niche Arts', 6, 'Design and print your own t-shirt', 'low', 17),
    ('Visual, Craft & Niche Arts', 6, 'Basic pattern cutting/tailoring', 'moderate', 18),
    ('Visual, Craft & Niche Arts', 6, 'Thrift and upcycle old clothing', 'low', 19),
    ('Visual, Craft & Niche Arts', 6, 'Embroidery', 'low', 20),
    ('Visual, Craft & Niche Arts', 6, 'Design a logo or personal brand mark', 'low', 21),
    ('Performance & Public Speaking', 7, 'Stand-up comedy — write and perform 5 minutes', 'low', 0),
    ('Performance & Public Speaking', 7, 'Acting / theatre workshop', 'moderate', 1),
    ('Performance & Public Speaking', 7, 'Dance class (freestyle, salsa, hip-hop)', 'moderate', 2),
    ('Performance & Public Speaking', 7, 'Public speaking / Toastmasters', 'low', 3),
    ('Performance & Public Speaking', 7, 'Storytelling night', 'low', 4),
    ('Performance & Public Speaking', 7, 'Improv workshop', 'moderate', 5),
    ('Performance & Public Speaking', 7, 'Flamenco or tango', 'moderate', 6),
    ('Performance & Public Speaking', 7, 'Breakdance or hip-hop choreography, beyond basics', 'moderate', 7),
    ('Performance & Public Speaking', 7, 'A folk dance from a country other than India', 'moderate', 8),
    ('Performance & Public Speaking', 7, 'Give a proper talk to a real audience (TEDx-style)', 'low', 9),
    ('Performance & Public Speaking', 7, 'Host and record a podcast episode', 'low', 10),
    ('Performance & Public Speaking', 7, 'Write and perform a monologue', 'low', 11),
    ('Performance & Public Speaking', 7, 'Help organize and take part in a flash mob', 'low', 12),
    ('Performance & Public Speaking', 7, 'Contribute to a public art installation', 'low', 13),
    ('Performance & Public Speaking', 7, 'Be an extra in a film, ad, or short film', 'low', 14),
    ('Performance & Public Speaking', 7, 'Enter and compete in a talent show', 'low', 15),
    ('Performance & Public Speaking', 7, 'A live radio/community broadcast segment', 'low', 16),
    ('Performance & Public Speaking', 7, 'MC an event — weddings, college fests, gatherings', 'low', 17),
    ('Performance & Public Speaking', 7, 'Get interviewed on camera, watch it back', 'low', 18),
    ('Culinary & Beverage Craft', 8, 'Cook a full meal from scratch, no recipe', 'low', 0),
    ('Culinary & Beverage Craft', 8, 'Bake bread', 'low', 1),
    ('Culinary & Beverage Craft', 8, 'Try an unfamiliar regional cuisine', 'low', 2),
    ('Culinary & Beverage Craft', 8, 'Home-brew something (kombucha, curd cultures)', 'low', 3),
    ('Culinary & Beverage Craft', 8, 'Master proper knife skills', 'low', 4),
    ('Culinary & Beverage Craft', 8, 'Try street food you''ve always been unsure about', 'low', 5),
    ('Culinary & Beverage Craft', 8, 'Mixology — proper mocktails at home', 'low', 6),
    ('Culinary & Beverage Craft', 8, 'Barista skills (shots, steaming, latte art)', 'moderate', 7),
    ('Culinary & Beverage Craft', 8, 'Tea tasting course', 'moderate', 8),
    ('Culinary & Beverage Craft', 8, 'Filter coffee tasting across regional styles', 'low', 9),
    ('Culinary & Beverage Craft', 8, 'Make cheese at home from scratch', 'low', 10),
    ('Culinary & Beverage Craft', 8, 'Ferment your own pickles', 'low', 11),
    ('Culinary & Beverage Craft', 8, 'Make chutneys/condiments completely from scratch', 'low', 12),
    ('Culinary & Beverage Craft', 8, 'Try a non-Indian fermented staple (miso, etc.)', 'low', 13),
    ('Culinary & Beverage Craft', 8, 'Make your own curd culture from scratch', 'low', 14),
    ('Culinary & Beverage Craft', 8, 'Dehydrate fruit/vegetables for preservation', 'low', 15),
    ('Culinary & Beverage Craft', 8, 'Make artisanal ice cream from scratch', 'low', 16),
    ('Culinary & Beverage Craft', 8, 'Make traditional Indian sweets from scratch', 'low', 17),
    ('Culinary & Beverage Craft', 8, 'Temper chocolate properly', 'low', 18),
    ('Culinary & Beverage Craft', 8, 'Make a layered cake completely from scratch', 'low', 19),
    ('Culinary & Beverage Craft', 8, 'Break down a whole chicken/fish yourself', 'low', 20),
    ('Culinary & Beverage Craft', 8, 'Master a mother sauce / base gravy from first principles', 'low', 21),
    ('Culinary & Beverage Craft', 8, 'Cook a multi-course meal for guests, timed', 'low', 22),
    ('Culinary & Beverage Craft', 8, 'Try a food you''re genuinely scared of', 'low', 23),
    ('Culinary & Beverage Craft', 8, 'Do a proper blind taste test with friends', 'low', 24),
    ('Culinary & Beverage Craft', 8, 'Cook one dish from every continent, over time', 'low', 25),
    ('Culinary & Beverage Craft', 8, 'Eat the spiciest thing you can handle', 'low', 26),
    ('Culinary & Beverage Craft', 8, 'Eat a full meal with hands only, mindfully', 'low', 27),
    ('Travel & Exploration', 9, 'A solo trip', 'moderate', 0),
    ('Travel & Exploration', 9, 'A backpacking trip, minimal luggage', 'moderate', 1),
    ('Travel & Exploration', 9, 'South Indian temple towns circuit', 'moderate', 2),
    ('Travel & Exploration', 9, 'Road trip through the Western Ghats', 'moderate', 3),
    ('Travel & Exploration', 9, 'Nilgiri Mountain Railway, scenic route', 'low', 4),
    ('Travel & Exploration', 9, 'Stay in a hostel, meet strangers', 'low', 5),
    ('Travel & Exploration', 9, 'A volunteer/work-exchange trip', 'moderate', 6),
    ('Travel & Exploration', 9, 'Hitchhike a short, safe route', 'low', 7),
    ('Travel & Exploration', 9, 'Cycle across an entire state', 'moderate', 8),
    ('Travel & Exploration', 9, 'Backpack across India — multi-state, weeks', 'moderate', 9),
    ('Travel & Exploration', 9, 'A multi-train hopping trip across states', 'moderate', 10),
    ('Travel & Exploration', 9, 'A trip with zero pre-booked plans', 'moderate', 11),
    ('Travel & Exploration', 9, 'A full week alone, traveling', 'moderate', 12),
    ('Travel & Exploration', 9, 'A trip to learn one region-specific skill', 'moderate', 13),
    ('Travel & Exploration', 9, 'Desert trip (Rajasthan)', 'moderate', 14),
    ('Travel & Exploration', 9, 'Visit the Himalayas', 'high', 15),
    ('Travel & Exploration', 9, 'An international trip', 'high', 16),
    ('Travel & Exploration', 9, 'Island trip (Andaman/Lakshadweep)', 'high', 17),
    ('Travel & Exploration', 9, 'Visit all coasts of India', 'high', 18),
    ('Travel & Exploration', 9, 'Cultural exchange or homestay abroad', 'high', 19),
    ('Extreme Geography & Nature Phenomena', 10, 'Highest accessible point in your home state', 'low', 0),
    ('Extreme Geography & Nature Phenomena', 10, 'A sea-level marker / coastline landmark', 'low', 1),
    ('Extreme Geography & Nature Phenomena', 10, 'Cross a state border deliberately, notice the shift', 'low', 2),
    ('Extreme Geography & Nature Phenomena', 10, 'A waterfall at full monsoon flow', 'low', 3),
    ('Extreme Geography & Nature Phenomena', 10, 'Walk through a mangrove forest', 'low', 4),
    ('Extreme Geography & Nature Phenomena', 10, 'Walk through a proper rainforest', 'moderate', 5),
    ('Extreme Geography & Nature Phenomena', 10, 'Explore a real cave system with a guide', 'moderate', 6),
    ('Extreme Geography & Nature Phenomena', 10, 'A salt pan / salt desert (Rann of Kutch)', 'moderate', 7),
    ('Extreme Geography & Nature Phenomena', 10, 'A night in the desert, under open sky', 'moderate', 8),
    ('Extreme Geography & Nature Phenomena', 10, 'A bioluminescent beach/water phenomenon', 'moderate', 9),
    ('Extreme Geography & Nature Phenomena', 10, 'See a river delta from above (drone/viewpoint)', 'moderate', 10),
    ('Extreme Geography & Nature Phenomena', 10, 'A unique geological formation (basalt, limestone)', 'moderate', 11),
    ('Extreme Geography & Nature Phenomena', 10, 'Experience snowfall for the first time', 'high', 12),
    ('Extreme Geography & Nature Phenomena', 10, 'Visit or dive at a coral reef', 'high', 13),
    ('Extreme Geography & Nature Phenomena', 10, 'Visit a live or dormant volcano', 'high', 14),
    ('Extreme Geography & Nature Phenomena', 10, 'Visit a glacier', 'high', 15),
    ('Extreme Geography & Nature Phenomena', 10, 'Watch a total solar eclipse — travel for it', 'high', 16),
    ('Extreme Geography & Nature Phenomena', 10, 'An extreme-temperature-record location', 'high', 17),
    ('Wilderness Survival & Outdoor Skills', 11, 'A proper multi-day trekking trail', 'moderate', 0),
    ('Wilderness Survival & Outdoor Skills', 11, 'Summit a Western Ghats peak', 'moderate', 1),
    ('Wilderness Survival & Outdoor Skills', 11, 'Rock climbing (indoor, then outdoor)', 'moderate', 2),
    ('Wilderness Survival & Outdoor Skills', 11, 'Rappelling', 'moderate', 3),
    ('Wilderness Survival & Outdoor Skills', 11, 'Camping under the stars', 'low', 4),
    ('Wilderness Survival & Outdoor Skills', 11, 'A night trek', 'low', 5),
    ('Wilderness Survival & Outdoor Skills', 11, 'A wildlife safari', 'moderate', 6),
    ('Wilderness Survival & Outdoor Skills', 11, 'A star-gazing trip away from city lights', 'low', 7),
    ('Wilderness Survival & Outdoor Skills', 11, 'Caving / spelunking', 'moderate', 8),
    ('Wilderness Survival & Outdoor Skills', 11, 'Start a fire without matches or a lighter', 'low', 9),
    ('Wilderness Survival & Outdoor Skills', 11, 'Build a survival shelter from scratch', 'low', 10),
    ('Wilderness Survival & Outdoor Skills', 11, 'Purify/filter water in the wild', 'low', 11),
    ('Wilderness Survival & Outdoor Skills', 11, 'Navigate with only a map and compass', 'low', 12),
    ('Wilderness Survival & Outdoor Skills', 11, 'Forage edible wild plants, with an expert', 'moderate', 13),
    ('Wilderness Survival & Outdoor Skills', 11, 'Tie 10 essential knots from memory', 'low', 14),
    ('Wilderness Survival & Outdoor Skills', 11, 'A certified first-aid/CPR course', 'moderate', 15),
    ('Wilderness Survival & Outdoor Skills', 11, 'Spend a night completely alone in nature', 'low', 16),
    ('Wilderness Survival & Outdoor Skills', 11, 'Read weather without a forecast app', 'low', 17),
    ('Wilderness Survival & Outdoor Skills', 11, 'Learn to identify local dangerous snakes/insects', 'low', 18),
    ('Science, Space & Sky', 12, 'Grow your own crystals at home', 'low', 0),
    ('Science, Space & Sky', 12, 'Build/use a telescope on the planets', 'moderate', 1),
    ('Science, Space & Sky', 12, 'A real chemistry experiment kit, safely', 'low', 2),
    ('Science, Space & Sky', 12, 'A volcano/chemical reaction demo', 'low', 3),
    ('Science, Space & Sky', 12, 'Star-trail photography', 'moderate', 4),
    ('Science, Space & Sky', 12, 'Contribute to a citizen science project', 'low', 5),
    ('Science, Space & Sky', 12, 'Track the ISS passing overhead', 'low', 6),
    ('Science, Space & Sky', 12, 'Build a simple electric motor from scratch', 'low', 7),
    ('Science, Space & Sky', 12, 'Extract DNA from a fruit at home', 'low', 8),
    ('Science, Space & Sky', 12, 'Do every exhibit at a planetarium/science center', 'low', 9),
    ('Science, Space & Sky', 12, 'Watch a meteor shower away from city lights', 'low', 10),
    ('Science, Space & Sky', 12, 'Photograph the Milky Way', 'moderate', 11),
    ('Science, Space & Sky', 12, 'Visit an observatory (Kodaikanal is nearby)', 'low', 12),
    ('Science, Space & Sky', 12, 'Identify 10 constellations by eye', 'low', 13),
    ('Science, Space & Sky', 12, 'Watch a rocket launch, live or livestream', 'low', 14),
    ('Science, Space & Sky', 12, 'A flight simulator session', 'moderate', 15),
    ('Science, Space & Sky', 12, 'Follow an ISRO mission start to finish', 'low', 16),
    ('Science, Space & Sky', 12, 'Learn the basics of how planes actually fly', 'low', 17),
    ('Science, Space & Sky', 12, 'Tour an airport operations area, if arrangeable', 'low', 18),
    ('Vehicles & Machines', 13, 'Drive manual transmission confidently', 'low', 0),
    ('Vehicles & Machines', 13, 'Learn basic bike/car mechanics', 'low', 1),
    ('Vehicles & Machines', 13, 'Ride a big touring motorcycle', 'moderate', 2),
    ('Vehicles & Machines', 13, 'Ride along with a long-haul truck driver', 'low', 3),
    ('Vehicles & Machines', 13, 'ATV / off-roading', 'moderate', 4),
    ('Vehicles & Machines', 13, 'Drone flying / racing', 'moderate', 5),
    ('Vehicles & Machines', 13, 'A small-aircraft flying lesson', 'high', 6),
    ('Gig Economy & Career Sampling', 14, 'Food delivery — real orders', 'low', 0),
    ('Gig Economy & Career Sampling', 14, 'Instant/quick-commerce delivery', 'low', 1),
    ('Gig Economy & Career Sampling', 14, 'E-commerce/parcel delivery', 'low', 2),
    ('Gig Economy & Career Sampling', 14, 'Bike taxi driving', 'low', 3),
    ('Gig Economy & Career Sampling', 14, 'Cab driving for a day', 'low', 4),
    ('Gig Economy & Career Sampling', 14, 'A store cashier shift', 'low', 5),
    ('Gig Economy & Career Sampling', 14, 'Wait tables at a restaurant for a shift', 'low', 6),
    ('Gig Economy & Career Sampling', 14, 'A barista/coffee shop shift', 'low', 7),
    ('Gig Economy & Career Sampling', 14, 'A warehouse picking/packing shift', 'low', 8),
    ('Gig Economy & Career Sampling', 14, 'A call center shift', 'low', 9),
    ('Gig Economy & Career Sampling', 14, 'Street vendor for a day', 'low', 10),
    ('Gig Economy & Career Sampling', 14, 'Event/wedding crew work', 'low', 11),
    ('Gig Economy & Career Sampling', 14, 'A security/gate duty shift', 'low', 12),
    ('Gig Economy & Career Sampling', 14, 'Assist a mechanic for a day', 'low', 13),
    ('Gig Economy & Career Sampling', 14, 'Assist an electrician or plumber for a day', 'low', 14),
    ('Gig Economy & Career Sampling', 14, 'Shadow a lawyer for a day', 'low', 15),
    ('Gig Economy & Career Sampling', 14, 'Shadow a journalist on a story', 'low', 16),
    ('Gig Economy & Career Sampling', 14, 'Spend a day on a film/TV production set', 'low', 17),
    ('Gig Economy & Career Sampling', 14, 'Shadow a chef in a fine-dining kitchen', 'low', 18),
    ('Gig Economy & Career Sampling', 14, 'Shadow an architect on a site visit', 'low', 19),
    ('Gig Economy & Career Sampling', 14, 'Follow a political campaign for a day', 'low', 20),
    ('Gig Economy & Career Sampling', 14, 'Spend a day in a real research lab', 'low', 21),
    ('Gig Economy & Career Sampling', 14, 'Shadow a radio jockey during a live show', 'low', 22),
    ('Gig Economy & Career Sampling', 14, 'Shadow a wildlife photographer or ranger', 'low', 23),
    ('Gig Economy & Career Sampling', 14, 'Cockpit jump-seat or airport ops visit', 'moderate', 24),
    ('Trades, DIY & Engineering Builds', 15, 'Basic carpentry — build a stool or shelf', 'moderate', 0),
    ('Trades, DIY & Engineering Builds', 15, 'Basic welding, supervised', 'moderate', 1),
    ('Trades, DIY & Engineering Builds', 15, '3D printing — design and print something', 'low', 2),
    ('Trades, DIY & Engineering Builds', 15, 'Soldering / basic electronics circuit', 'low', 3),
    ('Trades, DIY & Engineering Builds', 15, 'Leatherworking — make a wallet or strap', 'moderate', 4),
    ('Trades, DIY & Engineering Builds', 15, 'Bookbinding — make your own notebook', 'low', 5),
    ('Trades, DIY & Engineering Builds', 15, 'Candle making / soap making', 'low', 6),
    ('Trades, DIY & Engineering Builds', 15, 'A blacksmithing session', 'moderate', 7),
    ('Trades, DIY & Engineering Builds', 15, 'Sew a piece of clothing from scratch', 'low', 8),
    ('Trades, DIY & Engineering Builds', 15, 'Fix a basic plumbing issue yourself', 'low', 9),
    ('Trades, DIY & Engineering Builds', 15, 'Paint an entire room yourself', 'moderate', 10),
    ('Trades, DIY & Engineering Builds', 15, 'Build a garden bed and grow something in it', 'low', 11),
    ('Trades, DIY & Engineering Builds', 15, 'Set up a proper home theater/sound system', 'high', 12),
    ('Trades, DIY & Engineering Builds', 15, 'Upcycle old furniture', 'low', 13),
    ('Trades, DIY & Engineering Builds', 15, 'Install a shelf/fixture with proper tools', 'low', 14),
    ('Trades, DIY & Engineering Builds', 15, 'Rewire a simple light fixture, safely', 'low', 15),
    ('Trades, DIY & Engineering Builds', 15, 'Build a drone from individual parts', 'high', 16),
    ('Trades, DIY & Engineering Builds', 15, 'Build an RC car from a kit, then modify it', 'moderate', 17),
    ('Trades, DIY & Engineering Builds', 15, 'A robotics kit project (line follower)', 'moderate', 18),
    ('Trades, DIY & Engineering Builds', 15, 'Raspberry Pi/Arduino home automation', 'moderate', 19),
    ('Trades, DIY & Engineering Builds', 15, 'Build a working go-kart', 'high', 20),
    ('Trades, DIY & Engineering Builds', 15, 'Build a treehouse or outdoor structure', 'moderate', 21),
    ('Trades, DIY & Engineering Builds', 15, 'Assemble a custom PC and benchmark it', 'high', 22),
    ('Trades, DIY & Engineering Builds', 15, 'Build a small wind/water-powered device', 'low', 23),
    ('Trades, DIY & Engineering Builds', 15, 'Build a crystal radio from first principles', 'low', 24),
    ('Language & Communication', 16, 'Learn Indian Sign Language (ISL) basics', 'low', 0),
    ('Language & Communication', 16, 'Learn Braille — read a few lines by touch', 'low', 1),
    ('Language & Communication', 16, 'Learn Morse code', 'low', 2),
    ('Language & Communication', 16, 'Learn semaphore (flag signaling)', 'low', 3),
    ('Language & Communication', 16, 'Learn basic lip-reading', 'low', 4),
    ('Language & Communication', 16, 'A full day of only non-verbal communication', 'low', 5),
    ('Language & Communication', 16, 'Learn a regional script you can''t read', 'low', 6),
    ('Language & Communication', 16, 'Learn a whistling/loud-signal language', 'low', 7),
    ('Language & Communication', 16, 'Learn shorthand/stenography', 'low', 8),
    ('Language & Communication', 16, 'Learn the real slang/idioms of a language you study', 'low', 9),
    ('Language & Communication', 16, 'Translate a short piece of writing yourself', 'low', 10),
    ('Language & Communication', 16, 'Interpret live for someone in a real conversation', 'low', 11),
    ('Language & Communication', 16, 'Start a pen-pal or language exchange', 'low', 12),
    ('Language & Communication', 16, 'Learn the basics of an endangered language', 'low', 13),
    ('Language & Communication', 16, 'Deeply learn a culture''s etiquette before visiting', 'low', 14),
    ('Language & Communication', 16, 'Study a foreign country''s history in real depth', 'low', 15),
    ('Language & Communication', 16, 'Read a novel in its original language', 'low', 16),
    ('Language & Communication', 16, 'Watch a foreign film with no subtitles', 'low', 17),
    ('Culture, Festivals & Community', 17, 'Attend a wedding from a different religion/community', 'low', 0),
    ('Culture, Festivals & Community', 17, 'A folk dance from another Indian state', 'moderate', 1),
    ('Culture, Festivals & Community', 17, 'Cook a meal from a cuisine you''ve never made', 'low', 2),
    ('Culture, Festivals & Community', 17, 'A day in a village very different from your own', 'low', 3),
    ('Culture, Festivals & Community', 17, 'A tribal/indigenous festival, attended respectfully', 'moderate', 4),
    ('Culture, Festivals & Community', 17, 'Visit a museum, read every plaque', 'low', 5),
    ('Culture, Festivals & Community', 17, 'Be a tour guide for a visiting friend in your city', 'low', 6),
    ('Culture, Festivals & Community', 17, 'Host a themed international dinner night', 'low', 7),
    ('Culture, Festivals & Community', 17, 'Kumbh Mela', 'moderate', 8),
    ('Culture, Festivals & Community', 17, 'Holi in Mathura/Vrindavan', 'moderate', 9),
    ('Culture, Festivals & Community', 17, 'Diwali in Varanasi', 'moderate', 10),
    ('Culture, Festivals & Community', 17, 'Pushkar Camel Fair, Rajasthan', 'moderate', 11),
    ('Culture, Festivals & Community', 17, 'Rath Yatra, Puri', 'moderate', 12),
    ('Culture, Festivals & Community', 17, 'Bihu, Assam', 'moderate', 13),
    ('Culture, Festivals & Community', 17, 'Onam, Kerala — the full experience', 'moderate', 14),
    ('Culture, Festivals & Community', 17, 'Durga Puja in Kolkata', 'moderate', 15),
    ('Culture, Festivals & Community', 17, 'Thrissur Pooram, Kerala', 'moderate', 16),
    ('Culture, Festivals & Community', 17, 'Hornbill Festival, Nagaland', 'high', 17),
    ('Culture, Festivals & Community', 17, 'Rio Carnival, Brazil', 'high', 18),
    ('Culture, Festivals & Community', 17, 'Oktoberfest, Germany', 'high', 19),
    ('Culture, Festivals & Community', 17, 'La Tomatina, Spain', 'high', 20),
    ('Culture, Festivals & Community', 17, 'Day of the Dead, Mexico', 'high', 21),
    ('Culture, Festivals & Community', 17, 'Lantern Festival (Taiwan/Thailand)', 'high', 22),
    ('Culture, Festivals & Community', 17, 'Songkran, Thailand', 'high', 23),
    ('Culture, Festivals & Community', 17, 'Venice Carnival, Italy', 'high', 24),
    ('Culture, Festivals & Community', 17, 'Burning Man, USA', 'high', 25),
    ('Culture, Festivals & Community', 17, 'Edinburgh Fringe Festival, Scotland', 'high', 26),
    ('Culture, Festivals & Community', 17, 'A major music festival', 'moderate', 27),
    ('Culture, Festivals & Community', 17, 'A film festival', 'low', 28),
    ('Culture, Festivals & Community', 17, 'A comic-con', 'moderate', 29),
    ('Culture, Festivals & Community', 17, 'A literary festival (Jaipur Lit Fest)', 'low', 30),
    ('Culture, Festivals & Community', 17, 'A multi-region street food festival', 'low', 31),
    ('Games, Puzzles & Play', 18, 'Solve a Rubik''s cube from scratch', 'low', 0),
    ('Games, Puzzles & Play', 18, 'Complete an escape room', 'moderate', 1),
    ('Games, Puzzles & Play', 18, 'A 1000+ piece jigsaw puzzle', 'low', 2),
    ('Games, Puzzles & Play', 18, 'Learn a card game deeply (rummy, bridge, poker)', 'low', 3),
    ('Games, Puzzles & Play', 18, 'Memory sport techniques (memorize a deck)', 'low', 4),
    ('Games, Puzzles & Play', 18, 'A strategy board game, tournament-style', 'low', 5),
    ('Games, Puzzles & Play', 18, 'Geocaching', 'low', 6),
    ('Games, Puzzles & Play', 18, 'A city-wide scavenger hunt', 'low', 7),
    ('Games, Puzzles & Play', 18, 'Start a proper collection', 'moderate', 8),
    ('Games, Puzzles & Play', 18, 'A personal home library, properly cataloged', 'moderate', 9),
    ('Games, Puzzles & Play', 18, 'A monthly game night, made a real tradition', 'low', 10),
    ('Games, Puzzles & Play', 18, 'Wood whittling / carving', 'low', 11),
    ('Games, Puzzles & Play', 18, 'Build a scale model kit (plane, ship, car)', 'moderate', 12),
    ('Games, Puzzles & Play', 18, 'Kite-fighting', 'low', 13),
    ('Games, Puzzles & Play', 18, 'Advanced yo-yo tricks', 'low', 14),
    ('Games, Puzzles & Play', 18, 'Diabolo or poi spinning, no fire', 'low', 15),
    ('Games, Puzzles & Play', 18, 'Fully master one arcade game', 'low', 16),
    ('Games, Puzzles & Play', 18, 'Build and fly a model rocket', 'moderate', 17),
    ('Games, Puzzles & Play', 18, 'A Rubik''s variant (Pyraminx, Megaminx)', 'low', 18),
    ('Games, Puzzles & Play', 18, 'A fully committed themed costume party', 'low', 19),
    ('Games, Puzzles & Play', 18, 'A local esports tournament', 'low', 20),
    ('Games, Puzzles & Play', 18, 'A ranked strategy game (MOBA/RTS)', 'low', 21),
    ('Games, Puzzles & Play', 18, 'Speedrun a game you know well', 'low', 22),
    ('Games, Puzzles & Play', 18, 'Tabletop wargaming (Warhammer-style)', 'moderate', 23),
    ('Games, Puzzles & Play', 18, 'Game-master a tabletop RPG session', 'low', 24),
    ('Tech & Digital Experiments', 19, 'Build a simple website or app', 'low', 0),
    ('Tech & Digital Experiments', 19, 'Live-stream something for an hour', 'low', 1),
    ('Tech & Digital Experiments', 19, 'Edit and publish a YouTube video', 'low', 2),
    ('Tech & Digital Experiments', 19, 'Try a VR experience', 'moderate', 3),
    ('Tech & Digital Experiments', 19, '3D scan an object with your phone', 'low', 4),
    ('Tech & Digital Experiments', 19, 'Automate a repetitive task with code/no-code', 'low', 5),
    ('Tech & Digital Experiments', 19, 'Try generative AI for art/music, see how you feel', 'low', 6),
    ('Animals & Nature Interaction', 20, 'Horse riding', 'moderate', 0),
    ('Animals & Nature Interaction', 20, 'An ethical elephant sanctuary visit', 'moderate', 1),
    ('Animals & Nature Interaction', 20, 'Bird watching — ID 20 species', 'low', 2),
    ('Animals & Nature Interaction', 20, 'Camp specifically to spot wildlife', 'moderate', 3),
    ('Animals & Nature Interaction', 20, 'Hand-feed animals at an ethical sanctuary', 'moderate', 4),
    ('Animals & Nature Interaction', 20, 'Learn basic animal tracking', 'low', 5),
    ('Animals & Nature Interaction', 20, 'Visit a butterfly park', 'low', 6),
    ('Animals & Nature Interaction', 20, 'Volunteer at a wildlife rescue/rehab center', 'low', 7),
    ('Animals & Nature Interaction', 20, 'Join a bird-ringing/tagging activity', 'low', 8),
    ('Animals & Nature Interaction', 20, 'Join an annual wildlife census/count event', 'low', 9),
    ('Animals & Nature Interaction', 20, 'Build and maintain a bird feeder/nesting box', 'low', 10),
    ('Mind, Psychology & Inner Work', 21, 'A proper psychometric assessment (Big Five)', 'low', 0),
    ('Mind, Psychology & Inner Work', 21, 'Keep a dream journal for a month', 'low', 1),
    ('Mind, Psychology & Inner Work', 21, 'Attempt lucid dreaming techniques', 'low', 2),
    ('Mind, Psychology & Inner Work', 21, 'Build and actually use a memory palace', 'low', 3),
    ('Mind, Psychology & Inner Work', 21, 'Join or start a philosophy discussion group', 'low', 4),
    ('Mind, Psychology & Inner Work', 21, 'Stoic-style journaling for a month', 'low', 5),
    ('Mind, Psychology & Inner Work', 21, 'Guided breathwork (Wim Hof style)', 'low', 6),
    ('Mind, Psychology & Inner Work', 21, 'Sit in on a real therapy/counseling session', 'moderate', 7),
    ('Mind, Psychology & Inner Work', 21, 'A daily gratitude practice for 30 days', 'low', 8),
    ('Mind, Psychology & Inner Work', 21, 'Learn the basics of NLP', 'low', 9),
    ('Mind, Psychology & Inner Work', 21, 'A memento mori reflection ritual', 'low', 10),
    ('Mind, Psychology & Inner Work', 21, 'Study tarot/astrology as cultural history', 'low', 11),
    ('Mind, Psychology & Inner Work', 21, 'Give away something you genuinely value', 'low', 12),
    ('Mind, Psychology & Inner Work', 21, 'A professionally guided hypnosis session', 'moderate', 13),
    ('Mind, Psychology & Inner Work', 21, 'A full day of intentional silence', 'low', 14),
    ('Mind, Psychology & Inner Work', 21, 'Write your own eulogy, honestly', 'low', 15),
    ('Mind, Psychology & Inner Work', 21, 'A structured conversation about your fears', 'low', 16),
    ('Mind, Psychology & Inner Work', 21, 'Shadow work journaling', 'low', 17),
    ('Mind, Psychology & Inner Work', 21, 'Practice active listening deliberately for a week', 'low', 18),
    ('Civic, Legal & Financial Literacy', 22, 'File your own income tax return', 'low', 0),
    ('Civic, Legal & Financial Literacy', 22, 'Understand every line item on your payslip', 'low', 1),
    ('Civic, Legal & Financial Literacy', 22, 'File an RTI application', 'low', 2),
    ('Civic, Legal & Financial Literacy', 22, 'Vote, and understand the full process', 'low', 3),
    ('Civic, Legal & Financial Literacy', 22, 'Attend a gram panchayat/municipal ward meeting', 'low', 4),
    ('Civic, Legal & Financial Literacy', 22, 'Buy insurance deliberately, read every term', 'moderate', 5),
    ('Civic, Legal & Financial Literacy', 22, 'Learn how a will/estate plan actually works', 'low', 6),
    ('Civic, Legal & Financial Literacy', 22, 'Check and understand your credit score', 'low', 7),
    ('Civic, Legal & Financial Literacy', 22, 'Learn tenant/rental rights in your state', 'low', 8),
    ('Civic, Legal & Financial Literacy', 22, 'Learn to file a consumer complaint', 'low', 9),
    ('Civic, Legal & Financial Literacy', 22, 'Learn the process of registering a company', 'low', 10),
    ('Civic, Legal & Financial Literacy', 22, 'Walk through a bank loan application fully', 'low', 11),
    ('Civic, Legal & Financial Literacy', 22, 'Identify 3 government schemes you''re eligible for', 'low', 12),
    ('Civic, Legal & Financial Literacy', 22, 'Attend a civic tech / open-data hackathon', 'low', 13),
    ('Civic, Legal & Financial Literacy', 22, 'Fully read and understand a contract before signing', 'low', 14),
    ('Civic, Legal & Financial Literacy', 22, 'Understand how PF/EPF and gratuity work', 'low', 15),
    ('Civic, Legal & Financial Literacy', 22, 'Understand GST from both sides of a transaction', 'low', 16),
    ('Money & Hustle Experiments', 23, 'Run a tiny side-hustle for a month, track P&L', 'low', 0),
    ('Money & Hustle Experiments', 23, 'Sell something you made yourself', 'low', 1),
    ('Money & Hustle Experiments', 23, 'Practice negotiating a price down, respectfully', 'low', 2),
    ('Money & Hustle Experiments', 23, 'Make your first tracked investment', 'low', 3),
    ('Money & Hustle Experiments', 23, 'Try freelancing a small gig, start to finish', 'low', 4),
    ('Money & Hustle Experiments', 23, 'Barter a skill for something instead of cash', 'low', 5),
    ('Environmental Action & Sustainable Living', 24, 'A full zero-waste month', 'low', 0),
    ('Environmental Action & Sustainable Living', 24, 'A plastic-free week', 'low', 1),
    ('Environmental Action & Sustainable Living', 24, 'A personal carbon footprint audit', 'low', 2),
    ('Environmental Action & Sustainable Living', 24, 'Switch to a reusable daily-essentials kit', 'low', 3),
    ('Environmental Action & Sustainable Living', 24, 'Set up a small rainwater harvesting system', 'moderate', 4),
    ('Environmental Action & Sustainable Living', 24, 'Install and use a solar-powered device', 'moderate', 5),
    ('Environmental Action & Sustainable Living', 24, 'A permaculture short course', 'moderate', 6),
    ('Environmental Action & Sustainable Living', 24, 'Volunteer for a wildlife/forest conservation project', 'low', 7),
    ('Environmental Action & Sustainable Living', 24, 'Join an invasive-species removal drive', 'low', 8),
    ('Environmental Action & Sustainable Living', 24, 'Join a coral reef or river conservation program', 'moderate', 9),
    ('Environmental Action & Sustainable Living', 24, 'Learn to identify local trees/plants by name', 'low', 10),
    ('Environmental Action & Sustainable Living', 24, 'Join a citizen tree-mapping/urban greening initiative', 'low', 11),
    ('Environmental Action & Sustainable Living', 24, 'Help build or maintain a nature trail', 'low', 12),
    ('Sensory Exploration & Alternative Therapies', 25, 'A sensory deprivation float tank session', 'moderate', 0),
    ('Sensory Exploration & Alternative Therapies', 25, 'A full day blindfolded, with a trusted person around', 'low', 1),
    ('Sensory Exploration & Alternative Therapies', 25, 'A sound bath / gong meditation session', 'moderate', 2),
    ('Sensory Exploration & Alternative Therapies', 25, 'A contrast therapy session (sauna + ice bath)', 'moderate', 3),
    ('Sensory Exploration & Alternative Therapies', 25, 'Explore ASMR, see if it actually works for you', 'low', 4),
    ('Sensory Exploration & Alternative Therapies', 25, 'ID foods/spices by smell alone, blindfolded', 'low', 5),
    ('Sensory Exploration & Alternative Therapies', 25, 'A silent, screen-free sensory walk', 'low', 6),
    ('Sensory Exploration & Alternative Therapies', 25, 'Make your own perfume or scent blend', 'low', 7),
    ('Sensory Exploration & Alternative Therapies', 25, 'Make your own incense or dhoop', 'low', 8),
    ('Sensory Exploration & Alternative Therapies', 25, 'Try binaural beats, notice any real effect', 'low', 9),
    ('Sensory Exploration & Alternative Therapies', 25, 'Re-listen to a recording of a place you know well', 'low', 10),
    ('Sensory Exploration & Alternative Therapies', 25, 'Attempt basic echolocation, safely blindfolded', 'low', 11),
    ('Alternative Living Experiments', 26, 'Stay in a hostel dorm with strangers for a week', 'low', 0),
    ('Alternative Living Experiments', 26, 'Try a co-living space for a month', 'moderate', 1),
    ('Alternative Living Experiments', 26, 'House-sit for someone, fully responsible for their space', 'low', 2),
    ('Alternative Living Experiments', 26, 'A weekend fully off-grid', 'low', 3),
    ('Alternative Living Experiments', 26, 'Try van life / mobile living for a short stretch', 'moderate', 4),
    ('Alternative Living Experiments', 26, 'Live out of a single small bag for two weeks', 'low', 5),
    ('Alternative Living Experiments', 26, 'Try a capsule wardrobe for a full month', 'low', 6),
    ('Alternative Living Experiments', 26, 'A full digital minimalism month', 'low', 7),
    ('Alternative Living Experiments', 26, 'Live somewhere with a genuinely different climate', 'moderate', 8),
    ('Alternative Living Experiments', 26, 'A no-spend month, essentials only', 'low', 9),
    ('Health & Longevity', 27, 'Track your sleep for a month and optimize it', 'low', 0),
    ('Health & Longevity', 27, 'Structured intermittent fasting, properly guided', 'low', 1),
    ('Health & Longevity', 27, 'A full health/biohacking checkup', 'moderate', 2),
    ('Health & Longevity', 27, 'Daily yoga for a month straight', 'low', 3),
    ('Health & Longevity', 27, 'An Ayurveda consultation, try the recommendations', 'moderate', 4),
    ('Health & Longevity', 27, 'A posture/mobility audit, fix one bad habit', 'low', 5),
    ('Health & Longevity', 27, 'A full digital detox weekend', 'low', 6),
    ('Philanthropy & Giving', 28, 'Donate blood', 'low', 0),
    ('Philanthropy & Giving', 28, 'Organize a donation drive', 'low', 1),
    ('Philanthropy & Giving', 28, 'Sponsor a child''s education', 'high', 2),
    ('Philanthropy & Giving', 28, 'Start or join a community garden', 'low', 3),
    ('Philanthropy & Giving', 28, 'Join a beach/lake/river clean-up drive', 'low', 4),
    ('Philanthropy & Giving', 28, 'Volunteer your professional skill for free', 'low', 5),
    ('Philanthropy & Giving', 28, 'Cook and serve a meal for people who need it', 'low', 6),
    ('Legacy & Knowledge Transfer', 29, 'Write your own personal manifesto', 'low', 0),
    ('Legacy & Knowledge Transfer', 29, 'Build a family recipe book', 'low', 1),
    ('Legacy & Knowledge Transfer', 29, 'Build a personal portfolio website', 'low', 2),
    ('Legacy & Knowledge Transfer', 29, 'Create a time capsule', 'low', 3),
    ('Legacy & Knowledge Transfer', 29, 'Teach digital literacy to an elderly relative', 'low', 4),
    ('Legacy & Knowledge Transfer', 29, 'Restore an old family photo or heirloom', 'low', 5),
    ('Legacy & Knowledge Transfer', 29, 'Write ''letters to your future self''', 'low', 6),
    ('Legacy & Knowledge Transfer', 29, 'Compile your own ''lessons learned'' document', 'low', 7),
    ('Legacy & Knowledge Transfer', 29, 'Record a video message for a future milestone', 'low', 8),
    ('Legacy & Knowledge Transfer', 29, 'Create a simple will/asset list for your family', 'low', 9),
    ('Social & Novel Experiences', 30, 'Attend a live concert', 'moderate', 0),
    ('Social & Novel Experiences', 30, 'Attend a stand-up comedy show', 'moderate', 1),
    ('Social & Novel Experiences', 30, 'Go to a silent disco', 'moderate', 2),
    ('Social & Novel Experiences', 30, 'Attend a local festival you''ve never been to', 'low', 3),
    ('Social & Novel Experiences', 30, 'Volunteer for a cause you care about', 'low', 4),
    ('Social & Novel Experiences', 30, 'Mentor someone in something you''re good at', 'low', 5),
    ('Social & Novel Experiences', 30, 'Host a gathering/dinner for friends', 'low', 6),
    ('Social & Novel Experiences', 30, 'Go stargazing with an astronomy group', 'low', 7),
    ('Social & Novel Experiences', 30, 'Visit a planetarium or observatory', 'low', 8),
    ('Social & Novel Experiences', 30, 'Start and run a small business for a year', 'moderate', 9),
    ('Social & Novel Experiences', 30, 'Teach a class or workshop to others', 'low', 10),
    ('Social & Novel Experiences', 30, 'Mentor someone for a full term, not just once', 'low', 11),
    ('Social & Novel Experiences', 30, 'Write and publish a full book', 'moderate', 12),
    ('Social & Novel Experiences', 30, 'Plant a tree and track its growth over years', 'low', 13),
    ('Social & Novel Experiences', 30, 'Build something physical that outlives you', 'moderate', 14),
    ('Social & Novel Experiences', 30, 'Buy something significant with money saved for it', 'high', 15),
    ('Social & Novel Experiences', 30, 'Interview your oldest relative, record it', 'low', 16),
    ('Social & Novel Experiences', 30, 'Research your own family tree/genealogy', 'low', 17),
    ('Social & Novel Experiences', 30, 'Learn your hometown/region''s origin story', 'low', 18),
    ('Social & Novel Experiences', 30, 'Visit the place your ancestors are from', 'high', 19),
    ('Balance & Body Control', 31, 'Unicycling — learn to ride and turn', 'moderate', 0),
    ('Balance & Body Control', 31, 'Stilts walking', 'low', 1),
    ('Balance & Body Control', 31, 'Freestyle scooter tricks', 'moderate', 2),
    ('Balance & Body Control', 31, 'Longboard dancing (footwork tricks)', 'moderate', 3),
    ('Balance & Body Control', 31, 'Pole fitness basics', 'moderate', 4),
    ('Balance & Body Control', 31, 'Aerial silks / aerial hoop, beginner class', 'moderate', 5),
    ('Balance & Body Control', 31, 'Contortion/backbend basics, safely coached', 'moderate', 6),
    ('Balance & Body Control', 31, 'Advanced yoga poses — handstand, crow, wheel', 'low', 7),
    ('Balance & Body Control', 31, 'Freestyle football/soccer ball tricks', 'low', 8),
    ('Balance & Body Control', 31, 'Breakdancing power moves (headspin, windmill)', 'moderate', 9),
    ('Balance & Body Control', 31, 'Balance board / slack rail training', 'low', 10),
    ('Collecting & Restoration', 32, 'Start a coin collection (numismatics)', 'low', 0),
    ('Collecting & Restoration', 32, 'Start a stamp collection (philately)', 'low', 1),
    ('Collecting & Restoration', 32, 'Collect vinyl records, learn to care for them', 'moderate', 2),
    ('Collecting & Restoration', 32, 'Collect vintage postcards or matchboxes', 'low', 3),
    ('Collecting & Restoration', 32, 'Build a small old-currency collection', 'low', 4),
    ('Collecting & Restoration', 32, 'Restore an old bicycle to working condition', 'moderate', 5),
    ('Collecting & Restoration', 32, 'Restore a vintage mechanical watch', 'moderate', 6),
    ('Collecting & Restoration', 32, 'Restore an old radio or vintage electronics', 'moderate', 7),
    ('Collecting & Restoration', 32, 'Restore an old piece of furniture', 'moderate', 8),
    ('Collecting & Restoration', 32, 'Bring an old film camera back to working order', 'moderate', 9),
    ('Collecting & Restoration', 32, 'Hand-spin yarn from raw fibre', 'low', 10),
    ('Collecting & Restoration', 32, 'Natural-dye a piece of fabric', 'low', 11),
    ('Collecting & Restoration', 32, 'Weave on a traditional handloom', 'moderate', 12),
    ('Collecting & Restoration', 32, 'Learn hand-quilting', 'low', 13),
    ('Collecting & Restoration', 32, 'Make paper by hand from pulp', 'low', 14),
    ('Entrepreneurship & Startup Experiments', 33, 'Build and launch a real MVP', 'low', 0),
    ('Entrepreneurship & Startup Experiments', 33, 'Pitch an idea to a real investor or mentor', 'low', 1),
    ('Entrepreneurship & Startup Experiments', 33, 'Research and open a small online store', 'moderate', 2),
    ('Entrepreneurship & Startup Experiments', 33, 'Try dropshipping as a time-boxed experiment', 'low', 3),
    ('Entrepreneurship & Startup Experiments', 33, 'Paper-trade stocks for a full quarter', 'low', 4),
    ('Entrepreneurship & Startup Experiments', 33, 'Research the real economics of a franchise', 'low', 5),
    ('Entrepreneurship & Startup Experiments', 33, 'Write a full business plan for a fictional idea', 'low', 6),
    ('Entrepreneurship & Startup Experiments', 33, 'Attend a startup pitch night', 'low', 7),
    ('Entrepreneurship & Startup Experiments', 33, 'Deliberately network at a professional event', 'low', 8),
    ('Entrepreneurship & Startup Experiments', 33, 'Build a personal brand on one platform', 'low', 9),
    ('Entrepreneurship & Startup Experiments', 33, 'Cold-email someone you admire professionally', 'low', 10),
    ('Entrepreneurship & Startup Experiments', 33, 'Run a small paid ad campaign and measure it', 'moderate', 11),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Join a Model United Nations conference', 'low', 0),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Participate in a mock trial', 'low', 1),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Enter a formal debate tournament', 'low', 2),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Be a guest on someone else''s podcast', 'low', 3),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Write an op-ed and get it published', 'low', 4),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Defend an argument publicly against real pushback', 'low', 5),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Enter a spelling or word-based competition', 'low', 6),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Compete in speedcubing at an actual event', 'moderate', 7),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Enter a competitive programming contest', 'low', 8),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Compete in a formal rated chess tournament', 'low', 9),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Take part in a quiz/trivia competition', 'low', 10),
    ('Debate, Discourse & Competitive Mind Sports', 34, 'Try a competitive Toastmasters speech contest', 'low', 11),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Try underwater photography', 'moderate', 0),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Spearfishing, licensed and supervised', 'moderate', 1),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Go tide-pooling and identify what you find', 'low', 2),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Experience pearl diving (guided experience)', 'high', 3),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Go mushroom foraging with a real expert', 'moderate', 4),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Collect and identify rocks/minerals/crystals', 'low', 5),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Go fossil hunting at a known site', 'moderate', 6),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Basic amateur entomology — collect and identify insects', 'low', 7),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Set up a home weather station and log data', 'moderate', 8),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Learn celestial navigation with a sextant', 'moderate', 9),
    ('Underwater, Foraging & Field Naturalist Skills', 35, 'Track cloud types over a month', 'low', 10),
    ('Sailing, Rowing & Wind Sports', 36, 'Sail a dinghy, learn to helm it yourself', 'moderate', 0),
    ('Sailing, Rowing & Wind Sports', 36, 'Windsurfing', 'moderate', 1),
    ('Sailing, Rowing & Wind Sports', 36, 'Rowing / crew (single scull or team)', 'moderate', 2),
    ('Sailing, Rowing & Wind Sports', 36, 'Dragon boat racing', 'moderate', 3),
    ('Sailing, Rowing & Wind Sports', 36, 'Multi-day canoe touring', 'moderate', 4),
    ('Sailing, Rowing & Wind Sports', 36, 'Crew on a yacht race', 'high', 5),
    ('Sailing, Rowing & Wind Sports', 36, 'Learn sailing-specific knots and rigging', 'low', 6),
    ('Sailing, Rowing & Wind Sports', 36, 'Hang gliding', 'high', 7),
    ('Sailing, Rowing & Wind Sports', 36, 'Gliding — an unpowered aircraft with an instructor', 'high', 8),
    ('Sailing, Rowing & Wind Sports', 36, 'A short microlight flight experience', 'high', 9),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn basic accounting — debits and credits', 'low', 0),
    ('Financial & Business Literacy Deep-Dive', 37, 'Read and analyze a real company''s annual report', 'low', 1),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn crypto fundamentals, set up a wallet securely', 'low', 2),
    ('Financial & Business Literacy Deep-Dive', 37, 'A full investment analysis of a real property', 'low', 3),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn options/derivatives basics, conceptually', 'low', 4),
    ('Financial & Business Literacy Deep-Dive', 37, 'Build and maintain a personal net-worth tracker', 'low', 5),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn basic actuarial/insurance math', 'low', 6),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn how to value a small business', 'low', 7),
    ('Financial & Business Literacy Deep-Dive', 37, 'Understand mutual fund expense ratios deeply', 'low', 8),
    ('Financial & Business Literacy Deep-Dive', 37, 'Learn a real negotiation framework (BATNA)', 'low', 9),
    ('Pilgrimage & Sacred Journeys', 38, 'Char Dham Yatra', 'high', 0),
    ('Pilgrimage & Sacred Journeys', 38, 'Kailash Mansarovar trek', 'high', 1),
    ('Pilgrimage & Sacred Journeys', 38, 'Amarnath Yatra', 'high', 2),
    ('Pilgrimage & Sacred Journeys', 38, 'Sabarimala pilgrimage', 'moderate', 3),
    ('Pilgrimage & Sacred Journeys', 38, 'Camino de Santiago, Spain', 'high', 4),
    ('Pilgrimage & Sacred Journeys', 38, 'Visit the Vatican and St. Peter''s Basilica', 'high', 5),
    ('Pilgrimage & Sacred Journeys', 38, 'Visit Jerusalem''s Old City', 'high', 6),
    ('Pilgrimage & Sacred Journeys', 38, 'Walk a sacred river''s full ghat stretch', 'moderate', 7),
    ('Pilgrimage & Sacred Journeys', 38, 'Golden Temple, Amritsar + volunteer in langar', 'moderate', 8),
    ('Pilgrimage & Sacred Journeys', 38, 'Buddhist stupa circuit (Bodh Gaya, Sarnath)', 'moderate', 9),
    ('Advanced Photography & Visual Storytelling', 39, 'Shoot a time-lapse photography project', 'moderate', 0),
    ('Advanced Photography & Visual Storytelling', 39, 'Try drone cinematography', 'moderate', 1),
    ('Advanced Photography & Visual Storytelling', 39, 'Go on a dedicated wildlife photography expedition', 'high', 2),
    ('Advanced Photography & Visual Storytelling', 39, 'Shoot a full portrait photography series', 'moderate', 3),
    ('Advanced Photography & Visual Storytelling', 39, 'Shoot on film, develop it yourself', 'moderate', 4),
    ('Advanced Photography & Visual Storytelling', 39, 'Try long-exposure light painting', 'low', 5),
    ('Advanced Photography & Visual Storytelling', 39, 'Build a documentary-style photo essay', 'low', 6),
    ('Advanced Photography & Visual Storytelling', 39, 'Macro photography of insects or plants', 'moderate', 7),
    ('Advanced Photography & Visual Storytelling', 39, 'Architecture/panoramic photography of a cityscape', 'low', 8),
    ('Advanced Photography & Visual Storytelling', 39, 'A conceptual self-portrait photography project', 'low', 9),
    ('Circus & Aerial Arts', 40, 'Tightrope walking', 'moderate', 0),
    ('Circus & Aerial Arts', 40, 'Trapeze basics', 'moderate', 1),
    ('Circus & Aerial Arts', 40, 'Aerial rope (corde lisse)', 'moderate', 2),
    ('Circus & Aerial Arts', 40, 'Cyr wheel basics', 'moderate', 3),
    ('Circus & Aerial Arts', 40, 'Hula hoop tricks / hoop dance', 'low', 4),
    ('Circus & Aerial Arts', 40, 'Plate spinning', 'low', 5),
    ('Circus & Aerial Arts', 40, 'Acrobalance / partner acrobatics', 'moderate', 6),
    ('Circus & Aerial Arts', 40, 'A human pyramid team stunt', 'low', 7),
    ('Circus & Aerial Arts', 40, 'A clowning workshop', 'moderate', 8),
    ('Circus & Aerial Arts', 40, 'Staff or baton twirling', 'low', 9),
    ('Grooming, Styling & Body Literacy', 41, 'Basic men''s haircutting — a simple fade or trim', 'low', 0),
    ('Grooming, Styling & Body Literacy', 41, 'Basic women''s haircutting basics', 'low', 1),
    ('Grooming, Styling & Body Literacy', 41, 'Which hairstyles suit which face shapes', 'low', 2),
    ('Grooming, Styling & Body Literacy', 41, 'Style your own hair type properly', 'low', 3),
    ('Grooming, Styling & Body Literacy', 41, 'Basic blow-drying and heat-styling technique', 'low', 4),
    ('Grooming, Styling & Body Literacy', 41, 'Beard grooming and shaping properly', 'low', 5),
    ('Grooming, Styling & Body Literacy', 41, 'Basic braiding techniques', 'low', 6),
    ('Grooming, Styling & Body Literacy', 41, 'How barbers/stylists structure a haircut', 'low', 7),
    ('Grooming, Styling & Body Literacy', 41, 'A proper men''s skincare routine', 'low', 8),
    ('Grooming, Styling & Body Literacy', 41, 'A proper women''s skincare routine, reading labels', 'low', 9),
    ('Grooming, Styling & Body Literacy', 41, 'Learn your own skin type', 'low', 10),
    ('Grooming, Styling & Body Literacy', 41, 'Basic makeup application', 'low', 11),
    ('Grooming, Styling & Body Literacy', 41, 'Dress for your specific body type', 'low', 12),
    ('Grooming, Styling & Body Literacy', 41, 'Correct nail care and hygiene basics', 'low', 13),
    ('Grooming, Styling & Body Literacy', 41, 'How deodorant and body odor actually work', 'low', 14),
    ('Grooming, Styling & Body Literacy', 41, 'Essentials of male hormonal health', 'low', 15),
    ('Grooming, Styling & Body Literacy', 41, 'Essentials of female hormonal health', 'low', 16),
    ('Grooming, Styling & Body Literacy', 41, 'Doctor-recommended self-exams for early detection', 'low', 17),
    ('Grooming, Styling & Body Literacy', 41, 'Basic reproductive health facts, credible source', 'low', 18),
    ('Grooming, Styling & Body Literacy', 41, 'How metabolism differs between men and women', 'low', 19),
    ('Grooming, Styling & Body Literacy', 41, 'What changes to expect in the body with age', 'low', 20),
    ('Grooming, Styling & Body Literacy', 41, 'Common nutrient deficiencies by sex', 'low', 21),
    ('Grooming, Styling & Body Literacy', 41, 'How sleep, stress, and hormones interact', 'low', 22),
    ('Practical Safety & Everyday Preparedness', 42, 'A defensive driving course', 'moderate', 0),
    ('Practical Safety & Everyday Preparedness', 42, 'Change a flat tire yourself', 'low', 1),
    ('Practical Safety & Everyday Preparedness', 42, 'Jump-start a car battery', 'low', 2),
    ('Practical Safety & Everyday Preparedness', 42, 'Basic car maintenance (oil, tires, brakes)', 'low', 3),
    ('Practical Safety & Everyday Preparedness', 42, 'Use a fire extinguisher properly', 'low', 4),
    ('Practical Safety & Everyday Preparedness', 42, 'Earthquake and disaster preparedness for your region', 'low', 5),
    ('Practical Safety & Everyday Preparedness', 42, 'Recognize and avoid common scams', 'low', 6),
    ('Practical Safety & Everyday Preparedness', 42, 'Basic water-rescue technique', 'low', 7),
    ('Practical Safety & Everyday Preparedness', 42, 'Build a proper personal emergency kit', 'low', 8),
    ('Practical Safety & Everyday Preparedness', 42, 'First 5 minutes of common emergencies', 'low', 9),
    ('Practical Safety & Everyday Preparedness', 42, 'De-escalate a public safety situation calmly', 'low', 10),
    ('Practical Safety & Everyday Preparedness', 42, 'Basic home security — what actually deters break-ins', 'low', 11),
    ('Etiquette, Manners & Social Craft', 43, 'Formal dining etiquette', 'low', 0),
    ('Etiquette, Manners & Social Craft', 43, 'Tie at least 3 different tie knots', 'low', 1),
    ('Etiquette, Manners & Social Craft', 43, 'Correct table-setting for a formal meal', 'low', 2),
    ('Etiquette, Manners & Social Craft', 43, 'Business card and introduction etiquette', 'low', 3),
    ('Etiquette, Manners & Social Craft', 43, 'Write a proper formal letter/thank-you note', 'low', 4),
    ('Etiquette, Manners & Social Craft', 43, 'Basic ballroom dance steps (waltz/foxtrot)', 'moderate', 5),
    ('Etiquette, Manners & Social Craft', 43, 'Properly introduce two people to each other', 'low', 6),
    ('Etiquette, Manners & Social Craft', 43, 'Small talk techniques for a room of strangers', 'low', 7),
    ('Etiquette, Manners & Social Craft', 43, 'Hosting etiquette — being a good guest and host', 'low', 8),
    ('Etiquette, Manners & Social Craft', 43, 'Gracefully exit an unwanted conversation', 'low', 9),
    ('Home Economics & Life Admin Mastery', 44, 'Iron a shirt properly, collar and cuffs included', 'low', 0),
    ('Home Economics & Life Admin Mastery', 44, 'Sew a button and fix a hem by hand', 'low', 1),
    ('Home Economics & Life Admin Mastery', 44, 'An efficient clothes-folding system', 'low', 2),
    ('Home Economics & Life Admin Mastery', 44, 'A proper system for organizing important documents', 'low', 3),
    ('Home Economics & Life Admin Mastery', 44, 'A real meal-prep planning system for a busy week', 'low', 4),
    ('Home Economics & Life Admin Mastery', 44, 'Declutter a space using a real method', 'low', 5),
    ('Home Economics & Life Admin Mastery', 44, 'Pack a bag for a trip so nothing''s forgotten', 'low', 6),
    ('Home Economics & Life Admin Mastery', 44, 'A simple personal filing system, digital and physical', 'low', 7),
    ('Home Economics & Life Admin Mastery', 44, 'Basic stain removal for different fabric types', 'low', 8),
    ('Home Economics & Life Admin Mastery', 44, 'Properly store and preserve pantry staples', 'low', 9),
    ('Care & Responsibility Skills', 45, 'Safe infant-handling basics', 'low', 0),
    ('Care & Responsibility Skills', 45, 'Infant/child CPR specifically', 'low', 1),
    ('Care & Responsibility Skills', 45, 'Real responsibilities of pet ownership, a new species', 'low', 2),
    ('Care & Responsibility Skills', 45, 'Basic eldercare skills', 'low', 3),
    ('Care & Responsibility Skills', 45, 'How to babyproof a home properly', 'low', 4),
    ('Care & Responsibility Skills', 45, 'Build a real budget for a dependent', 'low', 5),
    ('Care & Responsibility Skills', 45, 'Volunteer at a place caring for a vulnerable group', 'low', 6),
    ('Care & Responsibility Skills', 45, 'Recognize distress in someone who can''t clearly communicate', 'low', 7),
    ('Care & Responsibility Skills', 45, 'Basic conflict mediation', 'low', 8),
    ('Iconic World Journeys', 46, 'An Antarctica expedition', 'high', 0),
    ('Iconic World Journeys', 46, 'Chase the Northern Lights in the Arctic Circle', 'high', 1),
    ('Iconic World Journeys', 46, 'Ride the Trans-Siberian Railway', 'high', 2),
    ('Iconic World Journeys', 46, 'Drive Route 66, USA, start to finish', 'high', 3),
    ('Iconic World Journeys', 46, 'An African safari (Serengeti or Masai Mara)', 'high', 4),
    ('Iconic World Journeys', 46, 'Overland travel along the historic Silk Road', 'high', 5),
    ('Iconic World Journeys', 46, 'The Trans-Mongolian Railway', 'high', 6),
    ('Iconic World Journeys', 46, 'Cross the Andes overland', 'high', 7),
    ('Iconic World Journeys', 46, 'Cruise the Scandinavian fjords', 'high', 8),
    ('Iconic World Journeys', 46, 'An Australian Outback road trip', 'high', 9),
    ('World Wonders & Landmarks', 47, 'The Pyramids of Giza, Egypt', 'high', 0),
    ('World Wonders & Landmarks', 47, 'The Great Wall of China', 'high', 1),
    ('World Wonders & Landmarks', 47, 'Machu Picchu, Peru', 'high', 2),
    ('World Wonders & Landmarks', 47, 'Petra, Jordan', 'high', 3),
    ('World Wonders & Landmarks', 47, 'The Colosseum, Rome', 'high', 4),
    ('World Wonders & Landmarks', 47, 'Angkor Wat, Cambodia', 'high', 5),
    ('World Wonders & Landmarks', 47, 'Christ the Redeemer, Rio de Janeiro', 'high', 6),
    ('World Wonders & Landmarks', 47, 'The Grand Canyon, USA', 'high', 7),
    ('World Wonders & Landmarks', 47, 'Niagara Falls', 'high', 8),
    ('World Wonders & Landmarks', 47, 'Stonehenge, England', 'high', 9),
    ('World Culinary & Craft Tourism', 48, 'Eat a meal at a Michelin-starred restaurant', 'high', 0),
    ('World Culinary & Craft Tourism', 48, 'Tour a wine region and understand the terroir', 'high', 1),
    ('World Culinary & Craft Tourism', 48, 'Tour a cheese-making region (France, Switzerland)', 'high', 2),
    ('World Culinary & Craft Tourism', 48, 'Tour a chocolate factory, bean to bar', 'moderate', 3),
    ('World Culinary & Craft Tourism', 48, 'Stay at a coffee farm during harvest', 'moderate', 4),
    ('World Culinary & Craft Tourism', 48, 'Stay at a tea plantation', 'moderate', 5),
    ('World Culinary & Craft Tourism', 48, 'Explore a spice market in another country', 'high', 6),
    ('World Culinary & Craft Tourism', 48, 'A full food-market crawl in a foreign city', 'high', 7),
    ('World Culinary & Craft Tourism', 48, 'A cooking class in the home country of that cuisine', 'high', 8),
    ('World Culinary & Craft Tourism', 48, 'Eat at a genuine farm-to-table restaurant', 'moderate', 9),
    ('World Wellness & Traditional Healing', 49, 'A Turkish hammam', 'high', 0),
    ('World Wellness & Traditional Healing', 49, 'A Japanese onsen (hot spring bath)', 'high', 1),
    ('World Wellness & Traditional Healing', 49, 'Traditional Thai massage', 'moderate', 2),
    ('World Wellness & Traditional Healing', 49, 'An Ayurvedic panchakarma treatment, over several days', 'moderate', 3),
    ('World Wellness & Traditional Healing', 49, 'A Russian banya', 'high', 4),
    ('World Wellness & Traditional Healing', 49, 'A Korean jjimjilbang (bathhouse) experience', 'high', 5),
    ('World Wellness & Traditional Healing', 49, 'Balinese traditional healing practices', 'high', 6),
    ('World Wellness & Traditional Healing', 49, 'A Moroccan hammam ritual', 'high', 7),
    ('World Wellness & Traditional Healing', 49, 'Shinrin-yoku (forest bathing), Japanese-style', 'low', 8),
    ('World Wellness & Traditional Healing', 49, 'A Traditional Chinese Medicine consultation', 'moderate', 9),
    ('Spectator Sports & Live World Events', 50, 'Watch a Test cricket match live at a stadium', 'moderate', 0),
    ('Spectator Sports & Live World Events', 50, 'Watch a Grand Slam tennis match', 'high', 1),
    ('Spectator Sports & Live World Events', 50, 'Watch a Formula 1 race live', 'high', 2),
    ('Spectator Sports & Live World Events', 50, 'Watch an Olympic event live, in person', 'high', 3),
    ('Spectator Sports & Live World Events', 50, 'Watch an IPL final live', 'moderate', 4),
    ('Spectator Sports & Live World Events', 50, 'Watch a FIFA World Cup match live', 'high', 5),
    ('Spectator Sports & Live World Events', 50, 'Attend a Super Bowl', 'high', 6),
    ('Spectator Sports & Live World Events', 50, 'Watch a major heavyweight boxing match live', 'high', 7),
    ('Spectator Sports & Live World Events', 50, 'Attend an Ashes cricket series match', 'high', 8),
    ('Spectator Sports & Live World Events', 50, 'Watch a major horse race (Grand National)', 'high', 9),
    ('Winter & Snow Sports', 51, 'Downhill skiing', 'high', 0),
    ('Winter & Snow Sports', 51, 'Snowboarding', 'high', 1),
    ('Winter & Snow Sports', 51, 'Cross-country skiing', 'high', 2),
    ('Winter & Snow Sports', 51, 'Ice climbing', 'high', 3),
    ('Winter & Snow Sports', 51, 'Snowshoeing', 'moderate', 4),
    ('Winter & Snow Sports', 51, 'Dog sledding', 'high', 5),
    ('Winter & Snow Sports', 51, 'A bobsled experience run', 'high', 6),
    ('Winter & Snow Sports', 51, 'Backcountry ski touring', 'high', 7),
    ('Winter & Snow Sports', 51, 'A luge experience', 'high', 8),
    ('Winter & Snow Sports', 51, 'Curling', 'moderate', 9),
    ('Motorsport & Off-Road Riding', 52, 'A rally driving experience day', 'moderate', 0),
    ('Motorsport & Off-Road Riding', 52, 'Motocross', 'moderate', 1),
    ('Motorsport & Off-Road Riding', 52, 'Dirt bike riding on a real trail', 'moderate', 2),
    ('Motorsport & Off-Road Riding', 52, 'Ride in a monster truck', 'moderate', 3),
    ('Motorsport & Off-Road Riding', 52, 'Watch or drive in a demolition derby', 'moderate', 4),
    ('Motorsport & Off-Road Riding', 52, 'Watch or try drag racing', 'moderate', 5),
    ('Motorsport & Off-Road Riding', 52, 'A proper drift car experience', 'moderate', 6),
    ('Motorsport & Off-Road Riding', 52, 'Quad bike racing', 'moderate', 7),
    ('Motorsport & Off-Road Riding', 52, 'Banger racing', 'moderate', 8),
    ('Motorsport & Off-Road Riding', 52, 'A kart endurance race (team format)', 'moderate', 9),
    ('Space & Zero-Gravity Experiences', 53, 'Experience a zero-gravity parabolic flight', 'high', 0),
    ('Space & Zero-Gravity Experiences', 53, 'Register interest in a suborbital spaceflight program', 'high', 1),
    ('Space & Zero-Gravity Experiences', 53, 'Attend a talk where a real astronaut is speaking', 'low', 2),
    ('Space & Zero-Gravity Experiences', 53, 'Tour an actual rocket launch site', 'moderate', 3),
    ('Space & Zero-Gravity Experiences', 53, 'Apply to or follow a citizen space program', 'low', 4),
    ('Space & Zero-Gravity Experiences', 53, 'Visit a space museum''s flown-artifact exhibit', 'low', 5),
    ('Space & Zero-Gravity Experiences', 53, 'Build and launch a high-altitude weather balloon', 'moderate', 6),
    ('Collector''s Deep Cuts', 54, 'Learn sneaker culture and collecting history', 'moderate', 0),
    ('Collector''s Deep Cuts', 54, 'Learn watch collecting — movements, value', 'high', 1),
    ('Collector''s Deep Cuts', 54, 'Start a comic book or trading card collection', 'moderate', 2),
    ('Collector''s Deep Cuts', 54, 'Collect vintage film cameras specifically', 'moderate', 3),
    ('Collector''s Deep Cuts', 54, 'Start collecting original art from local artists', 'moderate', 4),
    ('Collector''s Deep Cuts', 54, 'Pick one niche category and go deep on it', 'moderate', 5),
    ('Modern Recovery & Performance Tech', 55, 'Try a cryotherapy chamber session', 'moderate', 0),
    ('Modern Recovery & Performance Tech', 55, 'Try neurofeedback or biofeedback training', 'moderate', 1),
    ('Modern Recovery & Performance Tech', 55, 'Try an altitude training tent/room session', 'moderate', 2),
    ('Modern Recovery & Performance Tech', 55, 'Try compression therapy (boots or sleeves)', 'moderate', 3),
    ('Modern Recovery & Performance Tech', 55, 'Try an infrared sauna session', 'moderate', 4),
    ('Modern Recovery & Performance Tech', 55, 'Use a wearable deliberately to change one habit', 'low', 5),
    ('Modern Recovery & Performance Tech', 55, 'A real physiotherapy movement-screening assessment', 'moderate', 6),
    ('Working Animals & Falconry', 56, 'Try falconry with a trained bird of prey', 'moderate', 0),
    ('Working Animals & Falconry', 56, 'Watch or learn about sheepdog herding trials', 'low', 1),
    ('Working Animals & Falconry', 56, 'Try mounted archery (horse riding + archery)', 'moderate', 2),
    ('Working Animals & Falconry', 56, 'Learn basic clicker training with a dog', 'low', 3),
    ('Working Animals & Falconry', 56, 'Visit a facility with working dogs', 'low', 4),
    ('Signals, Locks & Hidden Systems', 57, 'Get a ham radio license, make an international contact', 'moderate', 0),
    ('Signals, Locks & Hidden Systems', 57, 'Learn ethical lock-picking (locksport) on your own locks', 'low', 1),
    ('Signals, Locks & Hidden Systems', 57, 'Learn how a mechanical safe/vault mechanism works', 'low', 2),
    ('Signals, Locks & Hidden Systems', 57, 'Learn basic cryptography, solve a real cipher', 'low', 3),
    ('Signals, Locks & Hidden Systems', 57, 'Try metal detecting, with proper permission', 'moderate', 4),
    ('Signals, Locks & Hidden Systems', 57, 'Learn CB radio communication and etiquette', 'low', 5),
    ('Sculpture & Dimensional Art', 58, 'Stone carving — shape a piece from raw stone', 'moderate', 0),
    ('Sculpture & Dimensional Art', 58, 'Wire sculpture — build a figure from bent wire', 'low', 1),
    ('Sculpture & Dimensional Art', 58, 'Ice sculpture, even a simple attempt', 'moderate', 2),
    ('Sculpture & Dimensional Art', 58, 'Plaster casting / mold-making a small object', 'low', 3),
    ('Sculpture & Dimensional Art', 58, 'Weld scrap metal into a piece of art', 'moderate', 4),
    ('Performance Novelties', 59, 'Ventriloquism', 'low', 0),
    ('Performance Novelties', 59, 'Freestyle rap / rap battle', 'low', 1),
    ('Performance Novelties', 59, 'Flair bartending, practiced with empty bottles', 'low', 2),
    ('Performance Novelties', 59, 'Mime performance', 'low', 3),
    ('Performance Novelties', 59, 'Puppeteering your own puppet', 'low', 4),
    ('Deep Nature Immersion & Rare Sightings', 60, 'Attend a firefly-watching event in season', 'low', 0),
    ('Deep Nature Immersion & Rare Sightings', 60, 'A whale-watching expedition', 'high', 1),
    ('Deep Nature Immersion & Rare Sightings', 60, 'A migratory bird-watching event (Siberian cranes)', 'moderate', 2),
    ('Deep Nature Immersion & Rare Sightings', 60, 'A night safari for nocturnal animals', 'moderate', 3),
    ('Deep Nature Immersion & Rare Sightings', 60, 'Olive ridley turtle nesting season, conservation site', 'moderate', 4),
    ('Deep Nature Immersion & Rare Sightings', 60, 'Witness a mass insect emergence event', 'low', 5)
) as v(category, category_order, title, cost, position)
on conflict (user_id, category, title) do nothing;
