-- ============================================================================
-- B-List seed, part 2 of 5
-- Travel & Exploration
--   ... Culture, Festivals & Community
-- ============================================================================
-- 183 items. Split out of 0015 because a single 78 KB statement is
-- a bad thing to paste into a browser SQL editor: a paste that arrives short
-- fails with a parse error somewhere in the middle, which tells you nothing
-- about what actually went wrong.
--
-- Run 0015_bucket_list.sql first for the table itself. Then run these five in
-- any order. Each is idempotent - re-running adds nothing and overwrites
-- nothing you have since ticked off or edited.
-- ============================================================================

insert into public.bucket_items (user_id, category, title, cost, position)
select u.id, v.category, v.title, v.cost, v.position
from auth.users u
cross join (values
    ('Travel & Exploration', 9, 'A solo trip', 'moderate', 0),
    ('Travel & Exploration', 9, 'A backpacking trip, minimal luggage', 'moderate', 1),
    ('Travel & Exploration', 9, 'South Indian temple towns circuit', 'moderate', 2),
    ('Travel & Exploration', 9, 'Road trip through the Western Ghats', 'moderate', 3),
    ('Travel & Exploration', 9, 'Nilgiri Mountain Railway, scenic route', 'low', 4),
    ('Travel & Exploration', 9, 'Stay in a hostel, meet strangers', 'low', 5),
    ('Travel & Exploration', 9, 'A volunteer/work-exchange trip', 'moderate', 6),
    ('Travel & Exploration', 9, 'Hitchhike a short, safe route', 'low', 7),
    ('Travel & Exploration', 9, 'Cycle across an entire state', 'moderate', 8),
    ('Travel & Exploration', 9, 'Backpack across India — multi-state, weeks', 'moderate', 9),
    ('Travel & Exploration', 9, 'A multi-train hopping trip across states', 'moderate', 10),
    ('Travel & Exploration', 9, 'A trip with zero pre-booked plans', 'moderate', 11),
    ('Travel & Exploration', 9, 'A full week alone, traveling', 'moderate', 12),
    ('Travel & Exploration', 9, 'A trip to learn one region-specific skill', 'moderate', 13),
    ('Travel & Exploration', 9, 'Desert trip (Rajasthan)', 'moderate', 14),
    ('Travel & Exploration', 9, 'Visit the Himalayas', 'high', 15),
    ('Travel & Exploration', 9, 'An international trip', 'high', 16),
    ('Travel & Exploration', 9, 'Island trip (Andaman/Lakshadweep)', 'high', 17),
    ('Travel & Exploration', 9, 'Visit all coasts of India', 'high', 18),
    ('Travel & Exploration', 9, 'Cultural exchange or homestay abroad', 'high', 19),
    ('Extreme Geography & Nature Phenomena', 10, 'Highest accessible point in your home state', 'low', 0),
    ('Extreme Geography & Nature Phenomena', 10, 'A sea-level marker / coastline landmark', 'low', 1),
    ('Extreme Geography & Nature Phenomena', 10, 'Cross a state border deliberately, notice the shift', 'low', 2),
    ('Extreme Geography & Nature Phenomena', 10, 'A waterfall at full monsoon flow', 'low', 3),
    ('Extreme Geography & Nature Phenomena', 10, 'Walk through a mangrove forest', 'low', 4),
    ('Extreme Geography & Nature Phenomena', 10, 'Walk through a proper rainforest', 'moderate', 5),
    ('Extreme Geography & Nature Phenomena', 10, 'Explore a real cave system with a guide', 'moderate', 6),
    ('Extreme Geography & Nature Phenomena', 10, 'A salt pan / salt desert (Rann of Kutch)', 'moderate', 7),
    ('Extreme Geography & Nature Phenomena', 10, 'A night in the desert, under open sky', 'moderate', 8),
    ('Extreme Geography & Nature Phenomena', 10, 'A bioluminescent beach/water phenomenon', 'moderate', 9),
    ('Extreme Geography & Nature Phenomena', 10, 'See a river delta from above (drone/viewpoint)', 'moderate', 10),
    ('Extreme Geography & Nature Phenomena', 10, 'A unique geological formation (basalt, limestone)', 'moderate', 11),
    ('Extreme Geography & Nature Phenomena', 10, 'Experience snowfall for the first time', 'high', 12),
    ('Extreme Geography & Nature Phenomena', 10, 'Visit or dive at a coral reef', 'high', 13),
    ('Extreme Geography & Nature Phenomena', 10, 'Visit a live or dormant volcano', 'high', 14),
    ('Extreme Geography & Nature Phenomena', 10, 'Visit a glacier', 'high', 15),
    ('Extreme Geography & Nature Phenomena', 10, 'Watch a total solar eclipse — travel for it', 'high', 16),
    ('Extreme Geography & Nature Phenomena', 10, 'An extreme-temperature-record location', 'high', 17),
    ('Wilderness Survival & Outdoor Skills', 11, 'A proper multi-day trekking trail', 'moderate', 0),
    ('Wilderness Survival & Outdoor Skills', 11, 'Summit a Western Ghats peak', 'moderate', 1),
    ('Wilderness Survival & Outdoor Skills', 11, 'Rock climbing (indoor, then outdoor)', 'moderate', 2),
    ('Wilderness Survival & Outdoor Skills', 11, 'Rappelling', 'moderate', 3),
    ('Wilderness Survival & Outdoor Skills', 11, 'Camping under the stars', 'low', 4),
    ('Wilderness Survival & Outdoor Skills', 11, 'A night trek', 'low', 5),
    ('Wilderness Survival & Outdoor Skills', 11, 'A wildlife safari', 'moderate', 6),
    ('Wilderness Survival & Outdoor Skills', 11, 'A star-gazing trip away from city lights', 'low', 7),
    ('Wilderness Survival & Outdoor Skills', 11, 'Caving / spelunking', 'moderate', 8),
    ('Wilderness Survival & Outdoor Skills', 11, 'Start a fire without matches or a lighter', 'low', 9),
    ('Wilderness Survival & Outdoor Skills', 11, 'Build a survival shelter from scratch', 'low', 10),
    ('Wilderness Survival & Outdoor Skills', 11, 'Purify/filter water in the wild', 'low', 11),
    ('Wilderness Survival & Outdoor Skills', 11, 'Navigate with only a map and compass', 'low', 12),
    ('Wilderness Survival & Outdoor Skills', 11, 'Forage edible wild plants, with an expert', 'moderate', 13),
    ('Wilderness Survival & Outdoor Skills', 11, 'Tie 10 essential knots from memory', 'low', 14),
    ('Wilderness Survival & Outdoor Skills', 11, 'A certified first-aid/CPR course', 'moderate', 15),
    ('Wilderness Survival & Outdoor Skills', 11, 'Spend a night completely alone in nature', 'low', 16),
    ('Wilderness Survival & Outdoor Skills', 11, 'Read weather without a forecast app', 'low', 17),
    ('Wilderness Survival & Outdoor Skills', 11, 'Learn to identify local dangerous snakes/insects', 'low', 18),
    ('Science, Space & Sky', 12, 'Grow your own crystals at home', 'low', 0),
    ('Science, Space & Sky', 12, 'Build/use a telescope on the planets', 'moderate', 1),
    ('Science, Space & Sky', 12, 'A real chemistry experiment kit, safely', 'low', 2),
    ('Science, Space & Sky', 12, 'A volcano/chemical reaction demo', 'low', 3),
    ('Science, Space & Sky', 12, 'Star-trail photography', 'moderate', 4),
    ('Science, Space & Sky', 12, 'Contribute to a citizen science project', 'low', 5),
    ('Science, Space & Sky', 12, 'Track the ISS passing overhead', 'low', 6),
    ('Science, Space & Sky', 12, 'Build a simple electric motor from scratch', 'low', 7),
    ('Science, Space & Sky', 12, 'Extract DNA from a fruit at home', 'low', 8),
    ('Science, Space & Sky', 12, 'Do every exhibit at a planetarium/science center', 'low', 9),
    ('Science, Space & Sky', 12, 'Watch a meteor shower away from city lights', 'low', 10),
    ('Science, Space & Sky', 12, 'Photograph the Milky Way', 'moderate', 11),
    ('Science, Space & Sky', 12, 'Visit an observatory (Kodaikanal is nearby)', 'low', 12),
    ('Science, Space & Sky', 12, 'Identify 10 constellations by eye', 'low', 13),
    ('Science, Space & Sky', 12, 'Watch a rocket launch, live or livestream', 'low', 14),
    ('Science, Space & Sky', 12, 'A flight simulator session', 'moderate', 15),
    ('Science, Space & Sky', 12, 'Follow an ISRO mission start to finish', 'low', 16),
    ('Science, Space & Sky', 12, 'Learn the basics of how planes actually fly', 'low', 17),
    ('Science, Space & Sky', 12, 'Tour an airport operations area, if arrangeable', 'low', 18),
    ('Vehicles & Machines', 13, 'Drive manual transmission confidently', 'low', 0),
    ('Vehicles & Machines', 13, 'Learn basic bike/car mechanics', 'low', 1),
    ('Vehicles & Machines', 13, 'Ride a big touring motorcycle', 'moderate', 2),
    ('Vehicles & Machines', 13, 'Ride along with a long-haul truck driver', 'low', 3),
    ('Vehicles & Machines', 13, 'ATV / off-roading', 'moderate', 4),
    ('Vehicles & Machines', 13, 'Drone flying / racing', 'moderate', 5),
    ('Vehicles & Machines', 13, 'A small-aircraft flying lesson', 'high', 6),
    ('Gig Economy & Career Sampling', 14, 'Food delivery — real orders', 'low', 0),
    ('Gig Economy & Career Sampling', 14, 'Instant/quick-commerce delivery', 'low', 1),
    ('Gig Economy & Career Sampling', 14, 'E-commerce/parcel delivery', 'low', 2),
    ('Gig Economy & Career Sampling', 14, 'Bike taxi driving', 'low', 3),
    ('Gig Economy & Career Sampling', 14, 'Cab driving for a day', 'low', 4),
    ('Gig Economy & Career Sampling', 14, 'A store cashier shift', 'low', 5),
    ('Gig Economy & Career Sampling', 14, 'Wait tables at a restaurant for a shift', 'low', 6),
    ('Gig Economy & Career Sampling', 14, 'A barista/coffee shop shift', 'low', 7),
    ('Gig Economy & Career Sampling', 14, 'A warehouse picking/packing shift', 'low', 8),
    ('Gig Economy & Career Sampling', 14, 'A call center shift', 'low', 9),
    ('Gig Economy & Career Sampling', 14, 'Street vendor for a day', 'low', 10),
    ('Gig Economy & Career Sampling', 14, 'Event/wedding crew work', 'low', 11),
    ('Gig Economy & Career Sampling', 14, 'A security/gate duty shift', 'low', 12),
    ('Gig Economy & Career Sampling', 14, 'Assist a mechanic for a day', 'low', 13),
    ('Gig Economy & Career Sampling', 14, 'Assist an electrician or plumber for a day', 'low', 14),
    ('Gig Economy & Career Sampling', 14, 'Shadow a lawyer for a day', 'low', 15),
    ('Gig Economy & Career Sampling', 14, 'Shadow a journalist on a story', 'low', 16),
    ('Gig Economy & Career Sampling', 14, 'Spend a day on a film/TV production set', 'low', 17),
    ('Gig Economy & Career Sampling', 14, 'Shadow a chef in a fine-dining kitchen', 'low', 18),
    ('Gig Economy & Career Sampling', 14, 'Shadow an architect on a site visit', 'low', 19),
    ('Gig Economy & Career Sampling', 14, 'Follow a political campaign for a day', 'low', 20),
    ('Gig Economy & Career Sampling', 14, 'Spend a day in a real research lab', 'low', 21),
    ('Gig Economy & Career Sampling', 14, 'Shadow a radio jockey during a live show', 'low', 22),
    ('Gig Economy & Career Sampling', 14, 'Shadow a wildlife photographer or ranger', 'low', 23),
    ('Gig Economy & Career Sampling', 14, 'Cockpit jump-seat or airport ops visit', 'moderate', 24),
    ('Trades, DIY & Engineering Builds', 15, 'Basic carpentry — build a stool or shelf', 'moderate', 0),
    ('Trades, DIY & Engineering Builds', 15, 'Basic welding, supervised', 'moderate', 1),
    ('Trades, DIY & Engineering Builds', 15, '3D printing — design and print something', 'low', 2),
    ('Trades, DIY & Engineering Builds', 15, 'Soldering / basic electronics circuit', 'low', 3),
    ('Trades, DIY & Engineering Builds', 15, 'Leatherworking — make a wallet or strap', 'moderate', 4),
    ('Trades, DIY & Engineering Builds', 15, 'Bookbinding — make your own notebook', 'low', 5),
    ('Trades, DIY & Engineering Builds', 15, 'Candle making / soap making', 'low', 6),
    ('Trades, DIY & Engineering Builds', 15, 'A blacksmithing session', 'moderate', 7),
    ('Trades, DIY & Engineering Builds', 15, 'Sew a piece of clothing from scratch', 'low', 8),
    ('Trades, DIY & Engineering Builds', 15, 'Fix a basic plumbing issue yourself', 'low', 9),
    ('Trades, DIY & Engineering Builds', 15, 'Paint an entire room yourself', 'moderate', 10),
    ('Trades, DIY & Engineering Builds', 15, 'Build a garden bed and grow something in it', 'low', 11),
    ('Trades, DIY & Engineering Builds', 15, 'Set up a proper home theater/sound system', 'high', 12),
    ('Trades, DIY & Engineering Builds', 15, 'Upcycle old furniture', 'low', 13),
    ('Trades, DIY & Engineering Builds', 15, 'Install a shelf/fixture with proper tools', 'low', 14),
    ('Trades, DIY & Engineering Builds', 15, 'Rewire a simple light fixture, safely', 'low', 15),
    ('Trades, DIY & Engineering Builds', 15, 'Build a drone from individual parts', 'high', 16),
    ('Trades, DIY & Engineering Builds', 15, 'Build an RC car from a kit, then modify it', 'moderate', 17),
    ('Trades, DIY & Engineering Builds', 15, 'A robotics kit project (line follower)', 'moderate', 18),
    ('Trades, DIY & Engineering Builds', 15, 'Raspberry Pi/Arduino home automation', 'moderate', 19),
    ('Trades, DIY & Engineering Builds', 15, 'Build a working go-kart', 'high', 20),
    ('Trades, DIY & Engineering Builds', 15, 'Build a treehouse or outdoor structure', 'moderate', 21),
    ('Trades, DIY & Engineering Builds', 15, 'Assemble a custom PC and benchmark it', 'high', 22),
    ('Trades, DIY & Engineering Builds', 15, 'Build a small wind/water-powered device', 'low', 23),
    ('Trades, DIY & Engineering Builds', 15, 'Build a crystal radio from first principles', 'low', 24),
    ('Language & Communication', 16, 'Learn Indian Sign Language (ISL) basics', 'low', 0),
    ('Language & Communication', 16, 'Learn Braille — read a few lines by touch', 'low', 1),
    ('Language & Communication', 16, 'Learn Morse code', 'low', 2),
    ('Language & Communication', 16, 'Learn semaphore (flag signaling)', 'low', 3),
    ('Language & Communication', 16, 'Learn basic lip-reading', 'low', 4),
    ('Language & Communication', 16, 'A full day of only non-verbal communication', 'low', 5),
    ('Language & Communication', 16, 'Learn a regional script you can''t read', 'low', 6),
    ('Language & Communication', 16, 'Learn a whistling/loud-signal language', 'low', 7),
    ('Language & Communication', 16, 'Learn shorthand/stenography', 'low', 8),
    ('Language & Communication', 16, 'Learn the real slang/idioms of a language you study', 'low', 9),
    ('Language & Communication', 16, 'Translate a short piece of writing yourself', 'low', 10),
    ('Language & Communication', 16, 'Interpret live for someone in a real conversation', 'low', 11),
    ('Language & Communication', 16, 'Start a pen-pal or language exchange', 'low', 12),
    ('Language & Communication', 16, 'Learn the basics of an endangered language', 'low', 13),
    ('Language & Communication', 16, 'Deeply learn a culture''s etiquette before visiting', 'low', 14),
    ('Language & Communication', 16, 'Study a foreign country''s history in real depth', 'low', 15),
    ('Language & Communication', 16, 'Read a novel in its original language', 'low', 16),
    ('Language & Communication', 16, 'Watch a foreign film with no subtitles', 'low', 17),
    ('Culture, Festivals & Community', 17, 'Attend a wedding from a different religion/community', 'low', 0),
    ('Culture, Festivals & Community', 17, 'A folk dance from another Indian state', 'moderate', 1),
    ('Culture, Festivals & Community', 17, 'Cook a meal from a cuisine you''ve never made', 'low', 2),
    ('Culture, Festivals & Community', 17, 'A day in a village very different from your own', 'low', 3),
    ('Culture, Festivals & Community', 17, 'A tribal/indigenous festival, attended respectfully', 'moderate', 4),
    ('Culture, Festivals & Community', 17, 'Visit a museum, read every plaque', 'low', 5),
    ('Culture, Festivals & Community', 17, 'Be a tour guide for a visiting friend in your city', 'low', 6),
    ('Culture, Festivals & Community', 17, 'Host a themed international dinner night', 'low', 7),
    ('Culture, Festivals & Community', 17, 'Kumbh Mela', 'moderate', 8),
    ('Culture, Festivals & Community', 17, 'Holi in Mathura/Vrindavan', 'moderate', 9),
    ('Culture, Festivals & Community', 17, 'Diwali in Varanasi', 'moderate', 10),
    ('Culture, Festivals & Community', 17, 'Pushkar Camel Fair, Rajasthan', 'moderate', 11),
    ('Culture, Festivals & Community', 17, 'Rath Yatra, Puri', 'moderate', 12),
    ('Culture, Festivals & Community', 17, 'Bihu, Assam', 'moderate', 13),
    ('Culture, Festivals & Community', 17, 'Onam, Kerala — the full experience', 'moderate', 14),
    ('Culture, Festivals & Community', 17, 'Durga Puja in Kolkata', 'moderate', 15),
    ('Culture, Festivals & Community', 17, 'Thrissur Pooram, Kerala', 'moderate', 16),
    ('Culture, Festivals & Community', 17, 'Hornbill Festival, Nagaland', 'high', 17),
    ('Culture, Festivals & Community', 17, 'Rio Carnival, Brazil', 'high', 18),
    ('Culture, Festivals & Community', 17, 'Oktoberfest, Germany', 'high', 19),
    ('Culture, Festivals & Community', 17, 'La Tomatina, Spain', 'high', 20),
    ('Culture, Festivals & Community', 17, 'Day of the Dead, Mexico', 'high', 21),
    ('Culture, Festivals & Community', 17, 'Lantern Festival (Taiwan/Thailand)', 'high', 22),
    ('Culture, Festivals & Community', 17, 'Songkran, Thailand', 'high', 23),
    ('Culture, Festivals & Community', 17, 'Venice Carnival, Italy', 'high', 24),
    ('Culture, Festivals & Community', 17, 'Burning Man, USA', 'high', 25),
    ('Culture, Festivals & Community', 17, 'Edinburgh Fringe Festival, Scotland', 'high', 26),
    ('Culture, Festivals & Community', 17, 'A major music festival', 'moderate', 27),
    ('Culture, Festivals & Community', 17, 'A film festival', 'low', 28),
    ('Culture, Festivals & Community', 17, 'A comic-con', 'moderate', 29),
    ('Culture, Festivals & Community', 17, 'A literary festival (Jaipur Lit Fest)', 'low', 30),
    ('Culture, Festivals & Community', 17, 'A multi-region street food festival', 'low', 31)
) as v(category, category_order, title, cost, position)
on conflict (user_id, category, title) do nothing;
