-- ============================================================================
-- B-List seed, part 3 of 5
-- Games, Puzzles & Play
--   ... Social & Novel Experiences
-- ============================================================================
-- 164 items. Split out of 0015 because a single 78 KB statement is
-- a bad thing to paste into a browser SQL editor: a paste that arrives short
-- fails with a parse error somewhere in the middle, which tells you nothing
-- about what actually went wrong.
--
-- Run 0015_bucket_list.sql first for the table itself. Then run these five in
-- any order. Each is idempotent - re-running adds nothing and overwrites
-- nothing you have since ticked off or edited.
-- ============================================================================

insert into public.bucket_items (user_id, category, title, cost, position)
select u.id, v.category, v.title, v.cost, v.position
from auth.users u
cross join (values
    ('Games, Puzzles & Play', 18, 'Solve a Rubik''s cube from scratch', 'low', 0),
    ('Games, Puzzles & Play', 18, 'Complete an escape room', 'moderate', 1),
    ('Games, Puzzles & Play', 18, 'A 1000+ piece jigsaw puzzle', 'low', 2),
    ('Games, Puzzles & Play', 18, 'Learn a card game deeply (rummy, bridge, poker)', 'low', 3),
    ('Games, Puzzles & Play', 18, 'Memory sport techniques (memorize a deck)', 'low', 4),
    ('Games, Puzzles & Play', 18, 'A strategy board game, tournament-style', 'low', 5),
    ('Games, Puzzles & Play', 18, 'Geocaching', 'low', 6),
    ('Games, Puzzles & Play', 18, 'A city-wide scavenger hunt', 'low', 7),
    ('Games, Puzzles & Play', 18, 'Start a proper collection', 'moderate', 8),
    ('Games, Puzzles & Play', 18, 'A personal home library, properly cataloged', 'moderate', 9),
    ('Games, Puzzles & Play', 18, 'A monthly game night, made a real tradition', 'low', 10),
    ('Games, Puzzles & Play', 18, 'Wood whittling / carving', 'low', 11),
    ('Games, Puzzles & Play', 18, 'Build a scale model kit (plane, ship, car)', 'moderate', 12),
    ('Games, Puzzles & Play', 18, 'Kite-fighting', 'low', 13),
    ('Games, Puzzles & Play', 18, 'Advanced yo-yo tricks', 'low', 14),
    ('Games, Puzzles & Play', 18, 'Diabolo or poi spinning, no fire', 'low', 15),
    ('Games, Puzzles & Play', 18, 'Fully master one arcade game', 'low', 16),
    ('Games, Puzzles & Play', 18, 'Build and fly a model rocket', 'moderate', 17),
    ('Games, Puzzles & Play', 18, 'A Rubik''s variant (Pyraminx, Megaminx)', 'low', 18),
    ('Games, Puzzles & Play', 18, 'A fully committed themed costume party', 'low', 19),
    ('Games, Puzzles & Play', 18, 'A local esports tournament', 'low', 20),
    ('Games, Puzzles & Play', 18, 'A ranked strategy game (MOBA/RTS)', 'low', 21),
    ('Games, Puzzles & Play', 18, 'Speedrun a game you know well', 'low', 22),
    ('Games, Puzzles & Play', 18, 'Tabletop wargaming (Warhammer-style)', 'moderate', 23),
    ('Games, Puzzles & Play', 18, 'Game-master a tabletop RPG session', 'low', 24),
    ('Tech & Digital Experiments', 19, 'Build a simple website or app', 'low', 0),
    ('Tech & Digital Experiments', 19, 'Live-stream something for an hour', 'low', 1),
    ('Tech & Digital Experiments', 19, 'Edit and publish a YouTube video', 'low', 2),
    ('Tech & Digital Experiments', 19, 'Try a VR experience', 'moderate', 3),
    ('Tech & Digital Experiments', 19, '3D scan an object with your phone', 'low', 4),
    ('Tech & Digital Experiments', 19, 'Automate a repetitive task with code/no-code', 'low', 5),
    ('Tech & Digital Experiments', 19, 'Try generative AI for art/music, see how you feel', 'low', 6),
    ('Animals & Nature Interaction', 20, 'Horse riding', 'moderate', 0),
    ('Animals & Nature Interaction', 20, 'An ethical elephant sanctuary visit', 'moderate', 1),
    ('Animals & Nature Interaction', 20, 'Bird watching — ID 20 species', 'low', 2),
    ('Animals & Nature Interaction', 20, 'Camp specifically to spot wildlife', 'moderate', 3),
    ('Animals & Nature Interaction', 20, 'Hand-feed animals at an ethical sanctuary', 'moderate', 4),
    ('Animals & Nature Interaction', 20, 'Learn basic animal tracking', 'low', 5),
    ('Animals & Nature Interaction', 20, 'Visit a butterfly park', 'low', 6),
    ('Animals & Nature Interaction', 20, 'Volunteer at a wildlife rescue/rehab center', 'low', 7),
    ('Animals & Nature Interaction', 20, 'Join a bird-ringing/tagging activity', 'low', 8),
    ('Animals & Nature Interaction', 20, 'Join an annual wildlife census/count event', 'low', 9),
    ('Animals & Nature Interaction', 20, 'Build and maintain a bird feeder/nesting box', 'low', 10),
    ('Mind, Psychology & Inner Work', 21, 'A proper psychometric assessment (Big Five)', 'low', 0),
    ('Mind, Psychology & Inner Work', 21, 'Keep a dream journal for a month', 'low', 1),
    ('Mind, Psychology & Inner Work', 21, 'Attempt lucid dreaming techniques', 'low', 2),
    ('Mind, Psychology & Inner Work', 21, 'Build and actually use a memory palace', 'low', 3),
    ('Mind, Psychology & Inner Work', 21, 'Join or start a philosophy discussion group', 'low', 4),
    ('Mind, Psychology & Inner Work', 21, 'Stoic-style journaling for a month', 'low', 5),
    ('Mind, Psychology & Inner Work', 21, 'Guided breathwork (Wim Hof style)', 'low', 6),
    ('Mind, Psychology & Inner Work', 21, 'Sit in on a real therapy/counseling session', 'moderate', 7),
    ('Mind, Psychology & Inner Work', 21, 'A daily gratitude practice for 30 days', 'low', 8),
    ('Mind, Psychology & Inner Work', 21, 'Learn the basics of NLP', 'low', 9),
    ('Mind, Psychology & Inner Work', 21, 'A memento mori reflection ritual', 'low', 10),
    ('Mind, Psychology & Inner Work', 21, 'Study tarot/astrology as cultural history', 'low', 11),
    ('Mind, Psychology & Inner Work', 21, 'Give away something you genuinely value', 'low', 12),
    ('Mind, Psychology & Inner Work', 21, 'A professionally guided hypnosis session', 'moderate', 13),
    ('Mind, Psychology & Inner Work', 21, 'A full day of intentional silence', 'low', 14),
    ('Mind, Psychology & Inner Work', 21, 'Write your own eulogy, honestly', 'low', 15),
    ('Mind, Psychology & Inner Work', 21, 'A structured conversation about your fears', 'low', 16),
    ('Mind, Psychology & Inner Work', 21, 'Shadow work journaling', 'low', 17),
    ('Mind, Psychology & Inner Work', 21, 'Practice active listening deliberately for a week', 'low', 18),
    ('Civic, Legal & Financial Literacy', 22, 'File your own income tax return', 'low', 0),
    ('Civic, Legal & Financial Literacy', 22, 'Understand every line item on your payslip', 'low', 1),
    ('Civic, Legal & Financial Literacy', 22, 'File an RTI application', 'low', 2),
    ('Civic, Legal & Financial Literacy', 22, 'Vote, and understand the full process', 'low', 3),
    ('Civic, Legal & Financial Literacy', 22, 'Attend a gram panchayat/municipal ward meeting', 'low', 4),
    ('Civic, Legal & Financial Literacy', 22, 'Buy insurance deliberately, read every term', 'moderate', 5),
    ('Civic, Legal & Financial Literacy', 22, 'Learn how a will/estate plan actually works', 'low', 6),
    ('Civic, Legal & Financial Literacy', 22, 'Check and understand your credit score', 'low', 7),
    ('Civic, Legal & Financial Literacy', 22, 'Learn tenant/rental rights in your state', 'low', 8),
    ('Civic, Legal & Financial Literacy', 22, 'Learn to file a consumer complaint', 'low', 9),
    ('Civic, Legal & Financial Literacy', 22, 'Learn the process of registering a company', 'low', 10),
    ('Civic, Legal & Financial Literacy', 22, 'Walk through a bank loan application fully', 'low', 11),
    ('Civic, Legal & Financial Literacy', 22, 'Identify 3 government schemes you''re eligible for', 'low', 12),
    ('Civic, Legal & Financial Literacy', 22, 'Attend a civic tech / open-data hackathon', 'low', 13),
    ('Civic, Legal & Financial Literacy', 22, 'Fully read and understand a contract before signing', 'low', 14),
    ('Civic, Legal & Financial Literacy', 22, 'Understand how PF/EPF and gratuity work', 'low', 15),
    ('Civic, Legal & Financial Literacy', 22, 'Understand GST from both sides of a transaction', 'low', 16),
    ('Money & Hustle Experiments', 23, 'Run a tiny side-hustle for a month, track P&L', 'low', 0),
    ('Money & Hustle Experiments', 23, 'Sell something you made yourself', 'low', 1),
    ('Money & Hustle Experiments', 23, 'Practice negotiating a price down, respectfully', 'low', 2),
    ('Money & Hustle Experiments', 23, 'Make your first tracked investment', 'low', 3),
    ('Money & Hustle Experiments', 23, 'Try freelancing a small gig, start to finish', 'low', 4),
    ('Money & Hustle Experiments', 23, 'Barter a skill for something instead of cash', 'low', 5),
    ('Environmental Action & Sustainable Living', 24, 'A full zero-waste month', 'low', 0),
    ('Environmental Action & Sustainable Living', 24, 'A plastic-free week', 'low', 1),
    ('Environmental Action & Sustainable Living', 24, 'A personal carbon footprint audit', 'low', 2),
    ('Environmental Action & Sustainable Living', 24, 'Switch to a reusable daily-essentials kit', 'low', 3),
    ('Environmental Action & Sustainable Living', 24, 'Set up a small rainwater harvesting system', 'moderate', 4),
    ('Environmental Action & Sustainable Living', 24, 'Install and use a solar-powered device', 'moderate', 5),
    ('Environmental Action & Sustainable Living', 24, 'A permaculture short course', 'moderate', 6),
    ('Environmental Action & Sustainable Living', 24, 'Volunteer for a wildlife/forest conservation project', 'low', 7),
    ('Environmental Action & Sustainable Living', 24, 'Join an invasive-species removal drive', 'low', 8),
    ('Environmental Action & Sustainable Living', 24, 'Join a coral reef or river conservation program', 'moderate', 9),
    ('Environmental Action & Sustainable Living', 24, 'Learn to identify local trees/plants by name', 'low', 10),
    ('Environmental Action & Sustainable Living', 24, 'Join a citizen tree-mapping/urban greening initiative', 'low', 11),
    ('Environmental Action & Sustainable Living', 24, 'Help build or maintain a nature trail', 'low', 12),
    ('Sensory Exploration & Alternative Therapies', 25, 'A sensory deprivation float tank session', 'moderate', 0),
    ('Sensory Exploration & Alternative Therapies', 25, 'A full day blindfolded, with a trusted person around', 'low', 1),
    ('Sensory Exploration & Alternative Therapies', 25, 'A sound bath / gong meditation session', 'moderate', 2),
    ('Sensory Exploration & Alternative Therapies', 25, 'A contrast therapy session (sauna + ice bath)', 'moderate', 3),
    ('Sensory Exploration & Alternative Therapies', 25, 'Explore ASMR, see if it actually works for you', 'low', 4),
    ('Sensory Exploration & Alternative Therapies', 25, 'ID foods/spices by smell alone, blindfolded', 'low', 5),
    ('Sensory Exploration & Alternative Therapies', 25, 'A silent, screen-free sensory walk', 'low', 6),
    ('Sensory Exploration & Alternative Therapies', 25, 'Make your own perfume or scent blend', 'low', 7),
    ('Sensory Exploration & Alternative Therapies', 25, 'Make your own incense or dhoop', 'low', 8),
    ('Sensory Exploration & Alternative Therapies', 25, 'Try binaural beats, notice any real effect', 'low', 9),
    ('Sensory Exploration & Alternative Therapies', 25, 'Re-listen to a recording of a place you know well', 'low', 10),
    ('Sensory Exploration & Alternative Therapies', 25, 'Attempt basic echolocation, safely blindfolded', 'low', 11),
    ('Alternative Living Experiments', 26, 'Stay in a hostel dorm with strangers for a week', 'low', 0),
    ('Alternative Living Experiments', 26, 'Try a co-living space for a month', 'moderate', 1),
    ('Alternative Living Experiments', 26, 'House-sit for someone, fully responsible for their space', 'low', 2),
    ('Alternative Living Experiments', 26, 'A weekend fully off-grid', 'low', 3),
    ('Alternative Living Experiments', 26, 'Try van life / mobile living for a short stretch', 'moderate', 4),
    ('Alternative Living Experiments', 26, 'Live out of a single small bag for two weeks', 'low', 5),
    ('Alternative Living Experiments', 26, 'Try a capsule wardrobe for a full month', 'low', 6),
    ('Alternative Living Experiments', 26, 'A full digital minimalism month', 'low', 7),
    ('Alternative Living Experiments', 26, 'Live somewhere with a genuinely different climate', 'moderate', 8),
    ('Alternative Living Experiments', 26, 'A no-spend month, essentials only', 'low', 9),
    ('Health & Longevity', 27, 'Track your sleep for a month and optimize it', 'low', 0),
    ('Health & Longevity', 27, 'Structured intermittent fasting, properly guided', 'low', 1),
    ('Health & Longevity', 27, 'A full health/biohacking checkup', 'moderate', 2),
    ('Health & Longevity', 27, 'Daily yoga for a month straight', 'low', 3),
    ('Health & Longevity', 27, 'An Ayurveda consultation, try the recommendations', 'moderate', 4),
    ('Health & Longevity', 27, 'A posture/mobility audit, fix one bad habit', 'low', 5),
    ('Health & Longevity', 27, 'A full digital detox weekend', 'low', 6),
    ('Philanthropy & Giving', 28, 'Donate blood', 'low', 0),
    ('Philanthropy & Giving', 28, 'Organize a donation drive', 'low', 1),
    ('Philanthropy & Giving', 28, 'Sponsor a child''s education', 'high', 2),
    ('Philanthropy & Giving', 28, 'Start or join a community garden', 'low', 3),
    ('Philanthropy & Giving', 28, 'Join a beach/lake/river clean-up drive', 'low', 4),
    ('Philanthropy & Giving', 28, 'Volunteer your professional skill for free', 'low', 5),
    ('Philanthropy & Giving', 28, 'Cook and serve a meal for people who need it', 'low', 6),
    ('Legacy & Knowledge Transfer', 29, 'Write your own personal manifesto', 'low', 0),
    ('Legacy & Knowledge Transfer', 29, 'Build a family recipe book', 'low', 1),
    ('Legacy & Knowledge Transfer', 29, 'Build a personal portfolio website', 'low', 2),
    ('Legacy & Knowledge Transfer', 29, 'Create a time capsule', 'low', 3),
    ('Legacy & Knowledge Transfer', 29, 'Teach digital literacy to an elderly relative', 'low', 4),
    ('Legacy & Knowledge Transfer', 29, 'Restore an old family photo or heirloom', 'low', 5),
    ('Legacy & Knowledge Transfer', 29, 'Write ''letters to your future self''', 'low', 6),
    ('Legacy & Knowledge Transfer', 29, 'Compile your own ''lessons learned'' document', 'low', 7),
    ('Legacy & Knowledge Transfer', 29, 'Record a video message for a future milestone', 'low', 8),
    ('Legacy & Knowledge Transfer', 29, 'Create a simple will/asset list for your family', 'low', 9),
    ('Social & Novel Experiences', 30, 'Attend a live concert', 'moderate', 0),
    ('Social & Novel Experiences', 30, 'Attend a stand-up comedy show', 'moderate', 1),
    ('Social & Novel Experiences', 30, 'Go to a silent disco', 'moderate', 2),
    ('Social & Novel Experiences', 30, 'Attend a local festival you''ve never been to', 'low', 3),
    ('Social & Novel Experiences', 30, 'Volunteer for a cause you care about', 'low', 4),
    ('Social & Novel Experiences', 30, 'Mentor someone in something you''re good at', 'low', 5),
    ('Social & Novel Experiences', 30, 'Host a gathering/dinner for friends', 'low', 6),
    ('Social & Novel Experiences', 30, 'Go stargazing with an astronomy group', 'low', 7),
    ('Social & Novel Experiences', 30, 'Visit a planetarium or observatory', 'low', 8),
    ('Social & Novel Experiences', 30, 'Start and run a small business for a year', 'moderate', 9),
    ('Social & Novel Experiences', 30, 'Teach a class or workshop to others', 'low', 10),
    ('Social & Novel Experiences', 30, 'Mentor someone for a full term, not just once', 'low', 11),
    ('Social & Novel Experiences', 30, 'Write and publish a full book', 'moderate', 12),
    ('Social & Novel Experiences', 30, 'Plant a tree and track its growth over years', 'low', 13),
    ('Social & Novel Experiences', 30, 'Build something physical that outlives you', 'moderate', 14),
    ('Social & Novel Experiences', 30, 'Buy something significant with money saved for it', 'high', 15),
    ('Social & Novel Experiences', 30, 'Interview your oldest relative, record it', 'low', 16),
    ('Social & Novel Experiences', 30, 'Research your own family tree/genealogy', 'low', 17),
    ('Social & Novel Experiences', 30, 'Learn your hometown/region''s origin story', 'low', 18),
    ('Social & Novel Experiences', 30, 'Visit the place your ancestors are from', 'high', 19)
) as v(category, category_order, title, cost, position)
on conflict (user_id, category, title) do nothing;
